import type {
  ConditionPromotionStatus,
  PresentationFamily,
  WardBrainConditionPromotionEntry,
} from "../../types/wardbrain";

const LIVE_ENGINE = "live-engine" satisfies ConditionPromotionStatus;
const SCAFFOLD_ONLY = "scaffold-only" satisfies ConditionPromotionStatus;

export const CONDITION_PROMOTION_REGISTRY: WardBrainConditionPromotionEntry[] = [
  {
    canonicalName: "Acute coronary syndrome",
    presentationFamilies: ["chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["ACS", "acute coronary syndrome", "MI", "myocardial infarction"],
    sourceAnchor: "NICE CG95",
    learnMoreKey: "acute-coronary-syndrome",
  },
  {
    canonicalName: "Pulmonary embolism",
    presentationFamilies: ["chest-pain", "breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["PE", "pulmonary embolism", "pulmonary embolus", "lung clot"],
    sourceAnchor: "NICE NG158",
    learnMoreKey: "pulmonary-embolism",
  },
  {
    canonicalName: "Acute aortic syndrome",
    presentationFamilies: ["chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["AAS", "acute aortic syndrome", "aortic dissection"],
    notes: "High-risk chest pain family diagnosis with future scope for dedicated scaffold emphasis.",
    learnMoreKey: "acute-aortic-syndrome",
  },
  {
    canonicalName: "Pneumothorax",
    presentationFamilies: ["chest-pain", "breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["pneumothorax", "PTX", "collapsed lung", "tension pneumothorax"],
    learnMoreKey: "pneumothorax",
  },
  {
    canonicalName: "GORD",
    presentationFamilies: ["chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["GORD", "GERD", "reflux", "acid reflux"],
    learnMoreKey: "gord",
  },
  {
    canonicalName: "Pneumonia",
    presentationFamilies: ["chest-pain", "breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["pneumonia", "chest infection", "CAP", "community acquired pneumonia"],
    learnMoreKey: "pneumonia",
  },
  {
    canonicalName: "Subarachnoid haemorrhage",
    presentationFamilies: ["headache"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["SAH", "subarachnoid haemorrhage", "subarachnoid hemorrhage"],
    sourceAnchor: "NICE CG150",
    learnMoreKey: "subarachnoid-haemorrhage",
  },
  {
    canonicalName: "Migraine",
    presentationFamilies: ["headache"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["migraine"],
    learnMoreKey: "migraine",
  },
  {
    canonicalName: "Meningitis / encephalitis",
    presentationFamilies: ["headache", "confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["meningitis", "encephalitis", "meningoencephalitis", "CNS infection"],
    sourceAnchor: "NICE NG143",
    learnMoreKey: "meningitis-encephalitis",
  },
  {
    canonicalName: "Stroke / neurological emergency",
    presentationFamilies: ["headache", "confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["stroke", "CVA", "cerebrovascular accident", "neurological emergency"],
    learnMoreKey: "stroke-neurological-emergency",
  },
  {
    canonicalName: "TIA",
    presentationFamilies: ["confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["tia", "transient ischaemic attack", "transient ischemic attack"],
    learnMoreKey: "tia",
  },
  {
    canonicalName: "Abdominal aortic aneurysm",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["AAA", "abdominal aortic aneurysm", "ruptured AAA", "leaking AAA"],
    sourceAnchor: "NICE NG156",
    learnMoreKey: "abdominal-aortic-aneurysm",
  },
  {
    canonicalName: "Mesenteric ischaemia",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "mesenteric ischaemia",
      "mesenteric ischemia",
      "bowel ischaemia",
      "bowel ischemia",
    ],
    learnMoreKey: "mesenteric-ischaemia",
  },
  {
    canonicalName: "Appendicitis",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["appendicitis", "acute appendicitis"],
    learnMoreKey: "appendicitis",
  },
  {
    canonicalName: "Acute pancreatitis",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "acute pancreatitis",
      "pancreatitis",
      "pancreatitis attack",
      "alcoholic pancreatitis",
      "gallstone pancreatitis",
    ],
    learnMoreKey: "acute-pancreatitis",
  },
  {
    canonicalName: "Perforated viscus",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "perforated viscus",
      "gi perforation",
      "bowel perforation",
      "perforated ulcer",
      "perforation",
    ],
    learnMoreKey: "perforated-viscus",
  },
  {
    canonicalName: "Ectopic pregnancy",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["ectopic pregnancy", "ruptured ectopic", "ectopic"],
    learnMoreKey: "ectopic-pregnancy",
  },
  {
    canonicalName: "Ovarian / acute pelvic pathology",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["ovarian torsion", "acute pelvic pathology", "ovarian cyst accident", "gynaecological acute pelvic pathology"],
    learnMoreKey: "ovarian-acute-pelvic-pathology",
  },
  {
    canonicalName: "Acute cholangitis",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "acute cholangitis",
      "ascending cholangitis",
      "cholangitis",
      "biliary sepsis",
      "obstructive jaundice with sepsis",
    ],
    sourceAnchor: "NICE CG188",
    learnMoreKey: "acute-cholangitis",
  },
  {
    canonicalName: "Acute cholecystitis",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "acute cholecystitis",
      "cholecystitis",
      "gallbladder infection",
      "inflamed gallbladder",
      "infected gallbladder",
      "acute calculous cholecystitis",
      "gallstone cholecystitis",
      "gallbladder inflammation",
    ],
    sourceAnchor: "NHS acute cholecystitis + NICE CG188",
    learnMoreKey: "acute-cholecystitis",
  },
  {
    canonicalName: "Choledocholithiasis / obstructive jaundice",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "choledocholithiasis",
      "common bile duct stone",
      "cbd stone",
      "bile duct stone",
      "biliary obstruction",
      "blocked bile duct",
      "duct stone",
      "jaundice from gallstone",
      "gallstone obstruction",
    ],
    sourceAnchor: "NICE CG188 + NHS gallstones",
    learnMoreKey: "choledocholithiasis-obstructive-jaundice",
  },
  {
    canonicalName: "Biliary colic / gallstone disease",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: LIVE_ENGINE,
    aliases: [
      "biliary colic",
      "gallstone pain",
      "gallstone attack",
      "symptomatic gallstones",
      "cholelithiasis",
      "recurrent biliary pain",
      "post-prandial ruq pain",
      "fatty-food ruq pain",
    ],
    sourceAnchor: "NICE CG188 + NHS gallstones",
    learnMoreKey: "biliary-colic-gallstone-disease",
  },
  {
    canonicalName: "Primary sclerosing cholangitis",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: SCAFFOLD_ONLY,
    aliases: ["primary sclerosing cholangitis", "psc"],
    notes:
      "Kept scaffold-only as a chronic cholestatic comparator; current scaffold wording is educational rather than an acute management pathway.",
    sourceAnchor: "NHS hepatology content + Anki medicine deck",
    learnMoreKey: "primary-sclerosing-cholangitis",
  },
  {
    canonicalName: "Primary biliary cholangitis",
    presentationFamilies: ["ruq-pain-jaundice"],
    promotionStatus: SCAFFOLD_ONLY,
    aliases: ["primary biliary cholangitis", "pbc"],
    notes:
      "Kept scaffold-only as a chronic cholestatic comparator; current scaffold wording is educational rather than an acute management pathway.",
    sourceAnchor: "NHS PBC content + Anki medicine deck",
    learnMoreKey: "primary-biliary-cholangitis",
  },
  {
    canonicalName: "Gastroenteritis",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["gastroenteritis", "gastro", "vomiting and diarrhoea", "V&D"],
    learnMoreKey: "gastroenteritis",
  },
  {
    canonicalName: "GI bleed",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["GI bleed", "gastrointestinal bleed", "UGIB", "LGIB"],
    sourceAnchor: "NICE CG141",
    learnMoreKey: "gi-bleed",
  },
  {
    canonicalName: "Sepsis",
    presentationFamilies: ["breathlessness-pleuritic-chest-pain", "acute-abdominal-pain", "confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["sepsis", "septic", "septic shock", "severe sepsis"],
    sourceAnchor: "NICE NG253",
    learnMoreKey: "sepsis",
  },
  {
    canonicalName: "UTI / urosepsis",
    presentationFamilies: ["acute-abdominal-pain", "confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["uti", "urinary tract infection", "urosepsis", "pyelonephritis"],
    learnMoreKey: "uti-urosepsis",
  },
  {
    canonicalName: "Delirium secondary to infection",
    presentationFamilies: ["confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["delirium"],
    learnMoreKey: "delirium-secondary-to-infection",
  },
  {
    canonicalName: "Viral illness",
    presentationFamilies: ["headache"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["viral illness", "viral infection", "flu-like illness", "viral syndrome"],
    notes: "Broad febrile illness placeholder in the live engine until a dedicated fever/febrile illness family exists.",
    learnMoreKey: "viral-illness",
  },
  {
    canonicalName: "Hypoglycaemia",
    presentationFamilies: ["confusion-delirium"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["hypoglycaemia", "hypoglycemia", "hypo", "low blood sugar"],
    learnMoreKey: "hypoglycaemia",
  },
  {
    canonicalName: "Pericarditis",
    presentationFamilies: ["chest-pain"],
    promotionStatus: SCAFFOLD_ONLY,
    aliases: ["pericarditis"],
    notes: "Seeded for future chest-pain family expansion; not yet promoted into live ranking.",
    learnMoreKey: "pericarditis",
  },
  {
    canonicalName: "Musculoskeletal chest pain",
    presentationFamilies: ["chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["musculoskeletal chest pain", "musculoskeletal pain", "costochondritis"],
    notes: "Useful benign comparator for future chest-pain broadening.",
    learnMoreKey: "musculoskeletal-chest-pain",
  },
  {
    canonicalName: "Tension headache",
    presentationFamilies: ["headache"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["tension headache"],
    notes: "Seeded as a future benign headache comparator.",
    learnMoreKey: "tension-headache",
  },
  {
    canonicalName: "Temporal arteritis",
    presentationFamilies: ["headache"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["temporal arteritis", "giant cell arteritis", "GCA"],
    notes: "Important to support educational coverage before live-engine promotion.",
    learnMoreKey: "temporal-arteritis",
  },
  {
    canonicalName: "Asthma exacerbation",
    presentationFamilies: ["breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["asthma exacerbation", "acute asthma", "asthma attack"],
    notes: "Seeded for future breathlessness family expansion.",
    learnMoreKey: "asthma-exacerbation",
  },
  {
    canonicalName: "COPD exacerbation",
    presentationFamilies: ["breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["copd exacerbation", "acute copd exacerbation", "infective exacerbation of copd"],
    notes: "Seeded for future breathlessness family expansion.",
    learnMoreKey: "copd-exacerbation",
  },
  {
    canonicalName: "Heart failure",
    presentationFamilies: ["breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["heart failure", "ccf", "congestive cardiac failure", "congestive heart failure"],
    learnMoreKey: "heart-failure",
  },
  {
    canonicalName: "Panic / anxiety",
    presentationFamilies: ["chest-pain", "breathlessness-pleuritic-chest-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["panic attack", "anxiety", "panic", "anxiety attack"],
    learnMoreKey: "panic-anxiety",
  },
  {
    canonicalName: "Cauda equina syndrome",
    presentationFamilies: ["acute-abdominal-pain"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["cauda equina syndrome", "cauda equina"],
    learnMoreKey: "cauda-equina-syndrome",
  },
  {
    canonicalName: "Testicular torsion",
    presentationFamilies: ["testicular-pain-scrotal-swelling"],
    promotionStatus: LIVE_ENGINE,
    aliases: ["testicular torsion", "torsion"],
    learnMoreKey: "testicular-torsion",
  },
];

export const CONDITION_PROMOTION_REGISTRY_BY_NAME = Object.fromEntries(
  CONDITION_PROMOTION_REGISTRY.map((entry) => [entry.canonicalName, entry]),
) as Record<string, WardBrainConditionPromotionEntry>;

export const LIVE_ENGINE_CONDITIONS = CONDITION_PROMOTION_REGISTRY
  .filter((entry) => entry.promotionStatus === LIVE_ENGINE)
  .map((entry) => entry.canonicalName);

export const CONDITION_PROMOTION_STATUS: Record<string, ConditionPromotionStatus> =
  Object.fromEntries(
    CONDITION_PROMOTION_REGISTRY.map((entry) => [entry.canonicalName, entry.promotionStatus]),
  );

export function getConditionsForFamily(family: PresentationFamily): WardBrainConditionPromotionEntry[] {
  return CONDITION_PROMOTION_REGISTRY.filter((entry) => entry.presentationFamilies.includes(family));
}
