import type { DiagnosisBoost, ExtractedFeatures } from "../types";

type DiagnosisBoostRule = {
  diagnosis: string;
  threshold: number;
  points: number;
  reason: string;
  features: string[];
  requiredAnyFeatures?: string[];
};

const DIAGNOSIS_BOOST_RULES: DiagnosisBoostRule[] = [
  {
    diagnosis: "Acute aortic syndrome",
    threshold: 3,
    points: 5,
    reason: "vascular catastrophe pattern",
    features: [
      "chest_pain",
      "sudden_onset",
      "tearing_pain",
      "back_radiation",
      "collapse",
      "hypertension",
    ],
  },
  {
    diagnosis: "Abdominal aortic aneurysm",
    threshold: 3,
    points: 5,
    reason: "AAA pattern",
    features: [
      "abdominal_pain",
      "back_radiation",
      "collapse",
      "pulsatile_abdomen",
      "smoker",
      "hypotension",
      "hypertension",
    ],
  },
  {
    diagnosis: "Subarachnoid haemorrhage",
    threshold: 2,
    points: 7,
    reason: "sudden severe headache pattern",
    features: ["thunderclap", "headache", "vomiting", "neck_stiffness", "collapse", "focal_neurology"],
    requiredAnyFeatures: ["thunderclap"],
  },
  {
    diagnosis: "Stroke / neurological emergency",
    threshold: 2,
    points: 4,
    reason: "neurological emergency pattern",
    features: ["confusion", "focal_neurology", "collapse"],
  },
  {
    diagnosis: "TIA",
    threshold: 2,
    points: 6,
    reason: "transient focal neurological pattern",
    features: ["focal_neurology", "transient_focal_deficit", "sudden_onset"],
    requiredAnyFeatures: ["transient_focal_deficit"],
  },
  {
    diagnosis: "Mesenteric ischaemia",
    threshold: 2,
    points: 9,
    reason: "mesenteric ischaemia pattern",
    features: ["abdominal_pain", "pain_out_of_proportion", "af", "collapse", "hypotension"],
    requiredAnyFeatures: ["pain_out_of_proportion"],
  },
  {
    diagnosis: "Acute pancreatitis",
    threshold: 3,
    points: 5,
    reason: "pancreatitis pattern",
    features: [
      "abdominal_pain",
      "back_radiation",
      "vomiting",
      "nausea",
      "alcohol_excess",
      "binge_drinking",
      "gallstone_context",
      "severe_constant_upper_abdominal_pain",
    ],
    requiredAnyFeatures: ["back_radiation", "vomiting", "alcohol_excess", "binge_drinking", "gallstone_context"],
  },
  {
    diagnosis: "Perforated viscus",
    threshold: 3,
    points: 8,
    reason: "perforated viscus pattern",
    features: [
      "abdominal_pain",
      "sudden_onset",
      "guarding_rigidity",
      "abdominal_movement_pain",
      "lying_still",
      "perforation_language",
      "peptic_ulcer_disease",
      "collapse",
      "hypotension",
    ],
    requiredAnyFeatures: ["guarding_rigidity", "abdominal_movement_pain", "lying_still", "perforation_language"],
  },
  {
    diagnosis: "Appendicitis",
    threshold: 4,
    points: 8,
    reason: "appendicitis pattern",
    features: [
      "abdominal_pain",
      "rif_pain",
      "migration_to_rif",
      "rif_tenderness",
      "anorexia",
      "fever",
      "nausea",
      "vomiting",
      "abdominal_movement_pain",
    ],
    requiredAnyFeatures: ["rif_pain", "migration_to_rif", "rif_tenderness"],
  },
  {
    diagnosis: "Ectopic pregnancy",
    threshold: 4,
    points: 7,
    reason: "ectopic pregnancy pattern",
    features: ["abdominal_pain", "pelvic_pain", "pregnancy_possible", "missed_period", "vaginal_bleeding", "collapse", "hypotension"],
    requiredAnyFeatures: ["pregnancy_possible", "missed_period", "vaginal_bleeding"],
  },
  {
    diagnosis: "Ovarian / acute pelvic pathology",
    threshold: 3,
    points: 5,
    reason: "acute pelvic pathology pattern",
    features: ["abdominal_pain", "pelvic_pain", "sudden_onset", "vomiting", "vaginal_bleeding"],
    requiredAnyFeatures: ["pelvic_pain", "vaginal_bleeding"],
  },
  {
    diagnosis: "Testicular torsion",
    threshold: 2,
    points: 8,
    reason: "testicular torsion pattern",
    features: ["unilateral_testicular_pain", "sudden_onset", "vomiting", "abdominal_pain"],
    requiredAnyFeatures: ["unilateral_testicular_pain"],
  },
  {
    diagnosis: "Cauda equina syndrome",
    threshold: 2,
    points: 8,
    reason: "cauda equina pattern",
    features: ["back_pain", "urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
    requiredAnyFeatures: ["urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
  },
  {
    diagnosis: "Hypoglycaemia",
    threshold: 3,
    points: 6,
    reason: "hypoglycaemia pattern",
    features: ["confusion", "collapse", "sweating", "diabetic_context", "hypoglycaemia_cue"],
    requiredAnyFeatures: ["diabetic_context", "hypoglycaemia_cue"],
  },
  {
    diagnosis: "UTI / urosepsis",
    threshold: 3,
    points: 5,
    reason: "urinary sepsis pattern",
    features: ["urinary_symptoms", "flank_pain", "fever", "rigors", "confusion", "hypotension"],
    requiredAnyFeatures: ["urinary_symptoms", "flank_pain"],
  },
  {
    diagnosis: "Acute cholangitis",
    threshold: 4,
    points: 6,
    reason: "acute cholangitis pattern",
    features: [
      "ruq_pain",
      "jaundice",
      "fever",
      "rigors",
      "gallstone_context",
      "hypotension",
      "confusion",
    ],
    requiredAnyFeatures: ["fever", "rigors"],
  },
  {
    diagnosis: "Acute cholecystitis",
    threshold: 4,
    points: 5,
    reason: "acute cholecystitis pattern",
    features: [
      "ruq_pain",
      "persistent_ruq_pain",
      "localized_ruq_tenderness",
      "murphys_sign",
      "fever",
      "nausea",
      "vomiting",
      "post_prandial_pain",
      "gallstone_context",
    ],
    requiredAnyFeatures: ["murphys_sign", "persistent_ruq_pain", "localized_ruq_tenderness"],
  },
  {
    diagnosis: "Choledocholithiasis / obstructive jaundice",
    threshold: 4,
    points: 5,
    reason: "obstructive jaundice pattern",
    features: [
      "jaundice",
      "dark_urine",
      "pale_stools",
      "pruritus",
      "obstructive_jaundice_language",
      "gallstone_context",
      "ruq_pain",
    ],
    requiredAnyFeatures: ["jaundice", "dark_urine", "pale_stools", "obstructive_jaundice_language"],
  },
  {
    diagnosis: "Biliary colic / gallstone disease",
    threshold: 4,
    points: 5,
    reason: "biliary colic pattern",
    features: [
      "ruq_pain",
      "post_prandial_pain",
      "recurrent_biliary_pain",
      "well_between_episodes",
      "gallstone_context",
      "nausea",
    ],
    requiredAnyFeatures: ["post_prandial_pain", "recurrent_biliary_pain", "well_between_episodes"],
  },
  {
    diagnosis: "Acute coronary syndrome",
    threshold: 3,
    points: 4,
    reason: "ACS pattern",
    features: [
      "chest_pain",
      "jaw_pain",
      "arm_pain",
      "sweating",
      "nausea",
      "indigestion_like_chest_pain",
      "abdominal_pain",
      "hypertension",
      "smoker",
      "sob",
      "collapse",
    ],
    requiredAnyFeatures: ["chest_pain", "jaw_pain", "arm_pain", "indigestion_like_chest_pain"],
  },
  {
    diagnosis: "Pulmonary embolism",
    threshold: 5,
    points: 5,
    reason: "PE pattern",
    features: [
      "chest_pain",
      "sob",
      "sudden_onset",
      "tachycardia",
      "tachypnoea",
      "pleuritic_pain",
      "hypoxia",
      "collapse",
      "recent_surgery",
      "immobility",
      "long_haul_travel",
    ],
  },
  {
    diagnosis: "Pneumothorax",
    threshold: 3,
    points: 9,
    reason: "pneumothorax pattern",
    features: [
      "sob",
      "pleuritic_pain",
      "unilateral_reduced_air_entry",
      "trauma",
      "sudden_onset",
      "tall_thin_habitus",
      "recent_chest_drain",
      "previous_pneumothorax",
      "smoker",
    ],
    requiredAnyFeatures: ["unilateral_reduced_air_entry", "pleuritic_pain", "trauma"],
  },
  {
    diagnosis: "Meningitis / encephalitis",
    threshold: 3,
    points: 5,
    reason: "meningitis / encephalitis pattern",
    features: [
      "confusion",
      "fever",
      "headache",
      "neck_stiffness",
      "vomiting",
      "photophobia",
      "shared_accommodation",
      "recent_infection",
    ],
    requiredAnyFeatures: ["headache", "neck_stiffness", "photophobia", "confusion"],
  },
  {
    diagnosis: "GI bleed",
    threshold: 2,
    points: 5,
    reason: "GI bleed instability pattern",
    features: ["gi_bleed", "pr_bleeding", "melaena", "haematemesis"],
  },
  {
    diagnosis: "Sepsis",
    threshold: 4,
    points: 5,
    reason: "sepsis pattern",
    features: ["fever", "hypothermia", "rigors", "infection_source", "hypotension", "tachycardia", "tachypnoea", "confusion", "sob", "collapse"],
    requiredAnyFeatures: ["fever", "hypothermia", "rigors", "infection_source"],
  },
  {
    diagnosis: "Musculoskeletal chest pain",
    threshold: 3,
    points: 5,
    reason: "musculoskeletal chest wall pattern",
    features: [
      "chest_pain",
      "reproducible_chest_wall_tenderness",
      "movement_related_chest_pain",
      "post_lifting_onset",
    ],
    requiredAnyFeatures: ["reproducible_chest_wall_tenderness", "movement_related_chest_pain"],
  },
  {
    diagnosis: "Migraine",
    threshold: 4,
    points: 4,
    reason: "migraine pattern",
    features: [
      "headache",
      "photophobia",
      "nausea",
      "visual_aura",
      "throbbing_headache",
      "unilateral_headache",
      "recurrent_headache",
      "well_intervals",
    ],
    requiredAnyFeatures: ["photophobia", "visual_aura", "throbbing_headache", "unilateral_headache"],
  },
  {
    diagnosis: "Tension headache",
    threshold: 3,
    points: 4,
    reason: "tension headache pattern",
    features: [
      "headache",
      "gradual_onset",
      "bilateral_headache",
      "band_like_headache",
      "stress_trigger",
      "poor_sleep",
    ],
    requiredAnyFeatures: ["bilateral_headache", "band_like_headache", "stress_trigger"],
  },
  {
    diagnosis: "Temporal arteritis",
    threshold: 3,
    points: 5,
    reason: "temporal arteritis pattern",
    features: [
      "headache",
      "temporal_headache",
      "scalp_tenderness",
      "jaw_claudication",
      "transient_visual_symptoms",
      "pmr_like_symptoms",
    ],
    requiredAnyFeatures: ["jaw_claudication", "scalp_tenderness", "transient_visual_symptoms"],
  },
  {
    diagnosis: "Asthma exacerbation",
    threshold: 4,
    points: 6,
    reason: "asthma exacerbation pattern",
    features: [
      "sob",
      "wheeze",
      "known_asthma",
      "recent_infection",
      "increased_inhaler_use",
      "difficulty_speaking",
      "tachypnoea",
      "hypoxia",
    ],
    requiredAnyFeatures: ["wheeze", "known_asthma", "increased_inhaler_use", "difficulty_speaking"],
  },
  {
    diagnosis: "Heart failure",
    threshold: 3,
    points: 5,
    reason: "heart failure pattern",
    features: ["sob", "orthopnoea", "ankle_swelling", "hypoxia", "tachypnoea"],
    requiredAnyFeatures: ["orthopnoea", "ankle_swelling"],
  },
  {
    diagnosis: "Panic / anxiety",
    threshold: 2,
    points: 4,
    reason: "panic / anxiety pattern",
    features: ["panic_features", "sob", "chest_pain", "tachypnoea"],
    requiredAnyFeatures: ["panic_features"],
  },
  {
    diagnosis: "COPD exacerbation",
    threshold: 4,
    points: 5,
    reason: "COPD exacerbation pattern",
    features: [
      "sob",
      "wheeze",
      "known_copd",
      "sputum_change",
      "productive_cough",
      "progressive_course",
      "hypoxia",
      "tachypnoea",
    ],
    requiredAnyFeatures: ["known_copd", "sputum_change", "progressive_course"],
  },
];

function has(features: ExtractedFeatures, key: string) {
  return features.matchedFeatures.includes(key);
}

export function getDiagnosisBoosts(features: ExtractedFeatures): DiagnosisBoost[] {
  return DIAGNOSIS_BOOST_RULES.flatMap((boostRule) => {
    if (
      boostRule.requiredAnyFeatures &&
      !boostRule.requiredAnyFeatures.some((feature) => has(features, feature))
    ) {
      return [];
    }

    const matchCount = boostRule.features.filter((feature) => has(features, feature)).length;

    if (matchCount < boostRule.threshold) {
      return [];
    }

    return [
      {
        diagnosis: boostRule.diagnosis,
        reason: boostRule.reason,
        points: boostRule.points,
      },
    ];
  });
}
