import type { FeatureWeightMap, SignatureGate } from "../types";
import { normaliseDiagnosisName } from "./diagnosisAliases";

export type DiagnosisRule = {
  name: string;
  supportive: string[];
  conflicting: string[];
  expectedImportant?: string[];
  supportiveWeights?: FeatureWeightMap;
  conflictingWeights?: FeatureWeightMap;
  strongSignatureGate?: SignatureGate;
};

export const DIAGNOSIS_RULES: DiagnosisRule[] = [
  {
    name: "Acute aortic syndrome",
    supportive: [
      "chestPain",
      "suddenOnset",
      "tearingPain",
      "backRadiation",
      "collapse",
      "hypertension",
    ],
    conflicting: ["fever"],
    expectedImportant: ["suddenOnset", "tearingPain", "backRadiation"],
  },
  {
    name: "Abdominal aortic aneurysm",
    supportive: [
      "abdominalPain",
      "backRadiation",
      "collapse",
      "pulsatileAbdomen",
      "smoker",
      "hypotension",
      "hypertension",
    ],
    conflicting: [],
    expectedImportant: ["collapse", "pulsatileAbdomen"],
  },
  {
    name: "Acute coronary syndrome",
    supportive: [
      "chestPain",
      "jawPain",
      "armPain",
      "sweating",
      "nausea",
      "indigestionLikeChestPain",
      "abdominalPain",
      "collapse",
      "hypertension",
      "smoker",
      "sob",
    ],
    conflicting: [
      "tearingPain",
      "pulsatileAbdomen",
      "backRadiation",
      "reproducibleChestWallTenderness",
      "movementRelatedChestPain",
      "postLiftingOnset",
    ],
    expectedImportant: ["chestPain", "jawPain", "armPain", "sweating", "indigestionLikeChestPain"],
    supportiveWeights: {
      chestPain: 3,
      jawPain: 4,
      armPain: 4,
      sweating: 3,
      nausea: 2,
      indigestionLikeChestPain: 4,
      abdominalPain: 1,
      collapse: 2,
      hypertension: 1,
      smoker: 1,
      sob: 2,
    },
    conflictingWeights: {
      reproducibleChestWallTenderness: 4,
      movementRelatedChestPain: 3,
      postLiftingOnset: 3,
    },
    strongSignatureGate: {
      features: ["chestPain", "jawPain", "armPain", "sweating", "indigestionLikeChestPain"],
      threshold: 2,
      cappedScore: 6,
    },
  },
  {
    name: "Pulmonary embolism",
    supportive: [
      "chestPain",
      "sob",
      "suddenOnset",
      "tachycardia",
      "tachypnoea",
      "collapse",
      "pleuriticPain",
      "hypoxia",
      "haemoptysis",
      "recentSurgery",
      "immobility",
      "longHaulTravel",
    ],
    conflicting: [
      "pulsatileAbdomen",
      "tearingPain",
      "backRadiation",
      "unilateralReducedAirEntry",
      "tallThinHabitus",
      "previousPneumothorax",
      "recentChestDrain",
      "reproducibleChestWallTenderness",
      "postLiftingOnset",
      "wheeze",
    ],
    expectedImportant: ["sob", "suddenOnset"],
    supportiveWeights: {
      chestPain: 3,
      suddenOnset: 3,
      tachycardia: 3,
      tachypnoea: 3,
      sob: 3,
      pleuriticPain: 3,
      hypoxia: 2,
      haemoptysis: 3,
      collapse: 3,
      recentSurgery: 2,
      immobility: 2,
      longHaulTravel: 2,
    },
    conflictingWeights: {
      unilateralReducedAirEntry: 2,
      tallThinHabitus: 1,
      previousPneumothorax: 1,
      recentChestDrain: 1,
      reproducibleChestWallTenderness: 3,
      postLiftingOnset: 3,
      wheeze: 2,
    },
    strongSignatureGate: {
      features: ["chestPain", "sob", "suddenOnset", "pleuriticPain", "hypoxia"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "GORD",
    supportive: [
      "chestPain",
      "indigestionLikeChestPain",
      "heartburn",
      "acidRegurgitation",
      "worseAfterMeals",
      "worseLyingFlat",
      "antacidRelief",
    ],
    conflicting: [
      "suddenOnset",
      "tearingPain",
      "backRadiation",
      "collapse",
      "pulsatileAbdomen",
      "hypotension",
    ],
    expectedImportant: ["indigestionLikeChestPain", "heartburn", "acidRegurgitation"],
    supportiveWeights: {
      chestPain: 1,
      indigestionLikeChestPain: 2,
      heartburn: 4,
      acidRegurgitation: 3,
      worseAfterMeals: 2,
      worseLyingFlat: 2,
      antacidRelief: 3,
    },
  },
  {
    name: "Mesenteric ischaemia",
    supportive: ["abdominalPain", "painOutOfProportion", "af", "collapse", "vomiting", "hypotension"],
    conflicting: ["chestPain", "diarrhoea"],
    expectedImportant: ["abdominalPain", "painOutOfProportion"],
    supportiveWeights: {
      abdominalPain: 1,
      painOutOfProportion: 7,
      af: 4,
      collapse: 3,
      hypotension: 3,
      vomiting: 0,
    },
    conflictingWeights: {
      chestPain: 2,
      diarrhoea: 1,
    },
    strongSignatureGate: {
      features: ["abdominalPain", "painOutOfProportion", "af", "collapse", "hypotension"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Acute pancreatitis",
    supportive: [
      "abdominalPain",
      "backRadiation",
      "vomiting",
      "nausea",
      "alcoholExcess",
      "bingeDrinking",
      "gallstoneContext",
      "severeConstantUpperAbdominalPain",
    ],
    conflicting: [
      "diarrhoea",
      "giBleed",
      "prBleeding",
      "melaena",
      "haematemesis",
      "localizedRuqTenderness",
      "murphysSign",
    ],
    expectedImportant: ["abdominalPain", "vomiting", "backRadiation"],
    supportiveWeights: {
      abdominalPain: 2,
      backRadiation: 3,
      vomiting: 2,
      nausea: 1,
      alcoholExcess: 2,
      bingeDrinking: 2,
      gallstoneContext: 2,
      severeConstantUpperAbdominalPain: 3,
    },
    conflictingWeights: {
      diarrhoea: 2,
      giBleed: 3,
      prBleeding: 3,
      melaena: 3,
      haematemesis: 3,
      localizedRuqTenderness: 2,
      murphysSign: 3,
    },
    strongSignatureGate: {
      features: [
        "abdominalPain",
        "backRadiation",
        "vomiting",
        "alcoholExcess",
        "bingeDrinking",
        "gallstoneContext",
        "severeConstantUpperAbdominalPain",
      ],
      threshold: 3,
      cappedScore: 2,
    },
  },
  {
    name: "Perforated viscus",
    supportive: [
      "abdominalPain",
      "suddenOnset",
      "guardingRigidity",
      "abdominalMovementPain",
      "perforationLanguage",
      "pepticUlcerDisease",
      "collapse",
      "hypotension",
    ],
    conflicting: ["diarrhoea", "chestPain"],
    expectedImportant: ["abdominalPain", "suddenOnset", "guardingRigidity"],
    supportiveWeights: {
      abdominalPain: 1,
      suddenOnset: 3,
      guardingRigidity: 6,
      abdominalMovementPain: 4,
      perforationLanguage: 5,
      pepticUlcerDisease: 2,
      collapse: 2,
      hypotension: 2,
    },
    conflictingWeights: {
      diarrhoea: 2,
      chestPain: 2,
    },
    strongSignatureGate: {
      features: [
        "abdominalPain",
        "suddenOnset",
        "guardingRigidity",
        "abdominalMovementPain",
        "perforationLanguage",
        "pepticUlcerDisease",
      ],
      threshold: 2,
      cappedScore: 5,
    },
  },
  {
    name: "Subarachnoid haemorrhage",
    supportive: ["thunderclap", "headache", "vomiting", "neckStiffness", "collapse", "focalNeurology"],
    conflicting: ["gradualOnset", "visualAura", "gradualSpreadPositiveSymptoms", "wellIntervals"],
    expectedImportant: ["thunderclap", "headache"],
    supportiveWeights: {
      thunderclap: 6,
      headache: 2,
      vomiting: 1,
      neckStiffness: 2,
      collapse: 3,
      focalNeurology: 2,
    },
    conflictingWeights: {
      gradualOnset: 3,
      visualAura: 3,
      gradualSpreadPositiveSymptoms: 4,
      wellIntervals: 2,
    },
    strongSignatureGate: {
      features: ["thunderclap"],
      threshold: 1,
      cappedScore: 4,
    },
  },
  {
    name: "Stroke / neurological emergency",
    supportive: ["confusion", "focalNeurology", "collapse", "suddenOnset"],
    conflicting: [],
    expectedImportant: ["focalNeurology", "confusion"],
  },
  {
    name: "Delirium secondary to infection",
    supportive: ["confusion", "fever", "infectionSource", "recentInfection", "fluctuation"],
    conflicting: ["focalNeurology", "thunderclap"],
    expectedImportant: ["confusion", "fluctuation"],
    supportiveWeights: {
      confusion: 4,
      fever: 2,
      infectionSource: 3,
      recentInfection: 2,
      fluctuation: 3,
    },
  },
  {
    name: "Gastroenteritis",
    supportive: ["abdominalPain", "diarrhoea", "vomiting", "fever"],
    conflicting: [
      "painOutOfProportion",
      "collapse",
      "af",
      "hypotension",
      "giBleed",
      "prBleeding",
      "ruqPain",
      "persistentRuqPain",
      "localizedRuqTenderness",
      "murphysSign",
      "gallstoneContext",
      "rifPain",
      "migrationToRIF",
      "pregnancyPossible",
      "missedPeriod",
      "vaginalBleeding",
      "unilateralTesticularPain",
    ],
    expectedImportant: ["abdominalPain", "diarrhoea"],
    conflictingWeights: {
      painOutOfProportion: 3,
      collapse: 3,
      hypotension: 3,
      giBleed: 4,
      prBleeding: 4,
      ruqPain: 2,
      persistentRuqPain: 3,
      localizedRuqTenderness: 3,
      murphysSign: 4,
      gallstoneContext: 2,
      rifPain: 3,
      migrationToRIF: 4,
      pregnancyPossible: 3,
      missedPeriod: 3,
      vaginalBleeding: 4,
      unilateralTesticularPain: 5,
    },
  },
  {
    name: "Acute cholangitis",
    supportive: [
      "ruqPain",
      "abdominalPain",
      "jaundice",
      "fever",
      "rigors",
      "nausea",
      "vomiting",
      "darkUrine",
      "paleStools",
      "obstructiveJaundiceLanguage",
      "gallstoneContext",
      "confusion",
      "hypotension",
      "tachycardia",
    ],
    conflicting: [
      "diarrhoea",
      "pruritus",
      "dryEyesMouth",
      "fatigue",
      "chronicCourse",
      "murphysSign",
      "postPrandialPain",
      "recurrentBiliaryPain",
    ],
    expectedImportant: ["ruqPain", "jaundice", "fever"],
    supportiveWeights: {
      ruqPain: 4,
      abdominalPain: 1,
      jaundice: 4,
      fever: 3,
      rigors: 4,
      nausea: 1,
      vomiting: 1,
      darkUrine: 2,
      paleStools: 2,
      obstructiveJaundiceLanguage: 3,
      gallstoneContext: 2,
      confusion: 1,
      hypotension: 2,
      tachycardia: 1,
    },
    conflictingWeights: {
      diarrhoea: 2,
      pruritus: 2,
      dryEyesMouth: 3,
      fatigue: 2,
      chronicCourse: 4,
      murphysSign: 3,
      postPrandialPain: 3,
      recurrentBiliaryPain: 3,
    },
    strongSignatureGate: {
      features: [
        "ruqPain",
        "jaundice",
        "fever",
        "rigors",
      ],
      threshold: 3,
      cappedScore: 0,
    },
  },
  {
    name: "Acute cholecystitis",
    supportive: [
      "ruqPain",
      "abdominalPain",
      "persistentRuqPain",
      "localizedRuqTenderness",
      "murphysSign",
      "fever",
      "nausea",
      "vomiting",
      "postPrandialPain",
      "gallstoneContext",
    ],
    conflicting: [
      "jaundice",
      "darkUrine",
      "paleStools",
      "obstructiveJaundiceLanguage",
      "rigors",
      "hypotension",
      "confusion",
      "wellBetweenEpisodes",
    ],
    expectedImportant: ["ruqPain", "persistentRuqPain", "murphysSign"],
    supportiveWeights: {
      ruqPain: 4,
      abdominalPain: 1,
      persistentRuqPain: 6,
      localizedRuqTenderness: 6,
      murphysSign: 6,
      fever: 4,
      nausea: 2,
      vomiting: 2,
      postPrandialPain: 3,
      gallstoneContext: 3,
    },
    conflictingWeights: {
      jaundice: 2,
      darkUrine: 2,
      paleStools: 2,
      obstructiveJaundiceLanguage: 3,
      rigors: 2,
      hypotension: 2,
      confusion: 2,
      wellBetweenEpisodes: 3,
    },
    strongSignatureGate: {
      features: [
        "ruqPain",
        "persistentRuqPain",
        "localizedRuqTenderness",
        "murphysSign",
        "fever",
        "gallstoneContext",
      ],
      threshold: 3,
      cappedScore: 1,
    },
  },
  {
    name: "Choledocholithiasis / obstructive jaundice",
    supportive: [
      "jaundice",
      "darkUrine",
      "paleStools",
      "pruritus",
      "obstructiveJaundiceLanguage",
      "gallstoneContext",
      "ruqPain",
      "abdominalPain",
    ],
    conflicting: [
      "fever",
      "rigors",
      "hypotension",
      "confusion",
      "chronicCourse",
      "dryEyesMouth",
      "ibdContext",
    ],
    expectedImportant: ["jaundice", "darkUrine", "paleStools"],
    supportiveWeights: {
      jaundice: 5,
      darkUrine: 3,
      paleStools: 3,
      pruritus: 2,
      obstructiveJaundiceLanguage: 5,
      gallstoneContext: 2,
      ruqPain: 1,
      abdominalPain: 1,
    },
    conflictingWeights: {
      fever: 2,
      rigors: 3,
      hypotension: 2,
      confusion: 2,
      chronicCourse: 1,
      dryEyesMouth: 2,
      ibdContext: 2,
    },
    strongSignatureGate: {
      features: [
        "jaundice",
        "darkUrine",
        "paleStools",
        "pruritus",
        "obstructiveJaundiceLanguage",
        "gallstoneContext",
      ],
      threshold: 3,
      cappedScore: 1,
    },
  },
  {
    name: "Biliary colic / gallstone disease",
    supportive: [
      "ruqPain",
      "abdominalPain",
      "postPrandialPain",
      "recurrentBiliaryPain",
      "wellBetweenEpisodes",
      "gallstoneContext",
      "nausea",
    ],
    conflicting: [
      "fever",
      "jaundice",
      "darkUrine",
      "paleStools",
      "rigors",
      "hypotension",
      "confusion",
      "persistentRuqPain",
      "localizedRuqTenderness",
      "murphysSign",
    ],
    expectedImportant: ["ruqPain", "postPrandialPain", "wellBetweenEpisodes"],
    supportiveWeights: {
      ruqPain: 3,
      abdominalPain: 1,
      postPrandialPain: 4,
      recurrentBiliaryPain: 4,
      wellBetweenEpisodes: 4,
      gallstoneContext: 3,
      nausea: 1,
    },
    conflictingWeights: {
      fever: 3,
      jaundice: 3,
      darkUrine: 2,
      paleStools: 2,
      rigors: 3,
      hypotension: 2,
      confusion: 2,
      persistentRuqPain: 3,
      localizedRuqTenderness: 2,
      murphysSign: 3,
    },
    strongSignatureGate: {
      features: [
        "ruqPain",
        "postPrandialPain",
        "recurrentBiliaryPain",
        "wellBetweenEpisodes",
        "gallstoneContext",
      ],
      threshold: 3,
      cappedScore: 0,
    },
  },
  {
    name: "Pneumonia",
    supportive: [
      "sob",
      "fever",
      "pleuriticPain",
      "hypoxia",
      "productiveCough",
      "infectionSource",
      "rigors",
      "progressiveCourse",
      "sputumChange",
    ],
    conflicting: ["suddenOnset", "collapse"],
    expectedImportant: ["sob", "fever", "productiveCough"],
    supportiveWeights: {
      productiveCough: 3,
      infectionSource: 2,
      rigors: 2,
      progressiveCourse: 3,
      sputumChange: 2,
      fever: 3,
      sob: 2,
      pleuriticPain: 2,
      hypoxia: 2,
    },
    conflictingWeights: {
      suddenOnset: 3,
      collapse: 3,
    },
  },
  {
    name: "Pneumothorax",
    supportive: [
      "chestPain",
      "sob",
      "pleuriticPain",
      "hypoxia",
      "suddenOnset",
      "unilateralReducedAirEntry",
      "tallThinHabitus",
      "recentChestDrain",
      "previousPneumothorax",
      "trauma",
      "smoker",
    ],
    conflicting: ["fever"],
    expectedImportant: ["suddenOnset", "sob", "pleuriticPain"],
    supportiveWeights: {
      suddenOnset: 4,
      hypoxia: 1,
      chestPain: 1,
      sob: 4,
      pleuriticPain: 5,
      unilateralReducedAirEntry: 10,
      tallThinHabitus: 5,
      recentChestDrain: 3,
      previousPneumothorax: 3,
      trauma: 3,
      smoker: 2,
    },
    strongSignatureGate: {
      features: [
        "pleuriticPain",
        "unilateralReducedAirEntry",
        "trauma",
        "tallThinHabitus",
        "previousPneumothorax",
      ],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Migraine",
    supportive: [
      "headache",
      "vomiting",
      "photophobia",
      "nausea",
      "visualAura",
      "throbbingHeadache",
      "unilateralHeadache",
      "recurrentHeadache",
      "wellIntervals",
    ],
    conflicting: ["thunderclap", "focalNeurology", "neckStiffness", "fever", "collapse"],
    expectedImportant: ["headache", "photophobia", "visualAura"],
    supportiveWeights: {
      headache: 2,
      photophobia: 3,
      nausea: 2,
      visualAura: 4,
      throbbingHeadache: 3,
      unilateralHeadache: 2,
      recurrentHeadache: 2,
      wellIntervals: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focalNeurology: 4,
      neckStiffness: 3,
      fever: 2,
      collapse: 3,
    },
    strongSignatureGate: {
      features: [
        "headache",
        "photophobia",
        "visualAura",
        "throbbingHeadache",
        "unilateralHeadache",
        "recurrentHeadache",
      ],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "Tension headache",
    supportive: [
      "headache",
      "gradualOnset",
      "bilateralHeadache",
      "bandLikeHeadache",
      "stressTrigger",
      "poorSleep",
    ],
    conflicting: [
      "thunderclap",
      "focalNeurology",
      "neckStiffness",
      "fever",
      "photophobia",
      "vomiting",
      "visualAura",
    ],
    expectedImportant: ["headache", "bilateralHeadache", "bandLikeHeadache"],
    supportiveWeights: {
      headache: 2,
      gradualOnset: 2,
      bilateralHeadache: 3,
      bandLikeHeadache: 4,
      stressTrigger: 2,
      poorSleep: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focalNeurology: 4,
      neckStiffness: 3,
      fever: 2,
      photophobia: 2,
      vomiting: 2,
      visualAura: 3,
    },
    strongSignatureGate: {
      features: ["headache", "bilateralHeadache", "bandLikeHeadache", "gradualOnset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Meningitis / encephalitis",
    supportive: [
      "confusion",
      "fever",
      "headache",
      "neckStiffness",
      "vomiting",
      "photophobia",
      "sharedAccommodation",
      "recentInfection",
    ],
    conflicting: [
      "ruqPain",
      "persistentRuqPain",
      "localizedRuqTenderness",
      "murphysSign",
      "postPrandialPain",
      "gallstoneContext",
    ],
    expectedImportant: ["fever", "headache", "neckStiffness"],
    supportiveWeights: {
      neckStiffness: 3,
      confusion: 3,
      photophobia: 3,
      sharedAccommodation: 1,
      recentInfection: 1,
    },
    conflictingWeights: {
      ruqPain: 2,
      persistentRuqPain: 3,
      localizedRuqTenderness: 3,
      murphysSign: 4,
      postPrandialPain: 2,
      gallstoneContext: 2,
    },
  },
  {
    name: "GI bleed",
    supportive: [
      "giBleed",
      "prBleeding",
      "melaena",
      "haematemesis",
      "collapse",
      "hypotension",
      "tachycardia",
      "vomiting",
      "abdominalPain",
      "alcoholExcess",
      "bingeDrinking",
      "pepticUlcerDisease",
      "nsaidUse",
    ],
    conflicting: ["diarrhoea"],
    expectedImportant: ["giBleed", "hypotension"],
    supportiveWeights: {
      giBleed: 4,
      prBleeding: 3,
      melaena: 3,
      haematemesis: 3,
      hypotension: 1,
      collapse: 2,
      tachycardia: 1,
      vomiting: 1,
      abdominalPain: 1,
      alcoholExcess: 1,
      bingeDrinking: 1,
      pepticUlcerDisease: 2,
      nsaidUse: 2,
    },
    strongSignatureGate: {
      features: ["giBleed", "prBleeding", "melaena", "haematemesis"],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Sepsis",
    supportive: [
      "fever",
      "hypothermia",
      "rigors",
      "infectionSource",
      "hypotension",
      "tachycardia",
      "tachypnoea",
      "confusion",
      "sob",
      "collapse",
    ],
    conflicting: [],
    expectedImportant: ["fever", "hypotension", "tachycardia"],
    supportiveWeights: {
      fever: 3,
      hypothermia: 3,
      rigors: 3,
      infectionSource: 3,
      hypotension: 1,
      tachycardia: 1,
      tachypnoea: 1,
      confusion: 3,
      sob: 1,
      collapse: 1,
    },
    strongSignatureGate: {
      features: ["fever", "hypothermia", "rigors", "infectionSource"],
      threshold: 1,
      cappedScore: 3,
    },
  },
  {
    name: "Viral illness",
    supportive: ["fever", "headache", "vomiting"],
    conflicting: ["hypotension", "collapse", "confusion"],
    expectedImportant: ["fever"],
    conflictingWeights: {
      hypotension: 4,
      collapse: 3,
      confusion: 3,
    },
  },
  {
    name: "Temporal arteritis",
    supportive: [
      "headache",
      "temporalHeadache",
      "scalpTenderness",
      "jawClaudication",
      "transientVisualSymptoms",
      "pmrLikeSymptoms",
    ],
    conflicting: ["thunderclap", "vomiting", "focalNeurology"],
    expectedImportant: ["temporalHeadache", "jawClaudication", "transientVisualSymptoms"],
    supportiveWeights: {
      temporalHeadache: 3,
      scalpTenderness: 3,
      jawClaudication: 5,
      transientVisualSymptoms: 4,
      pmrLikeSymptoms: 3,
      headache: 1,
    },
    strongSignatureGate: {
      features: ["temporalHeadache", "jawClaudication", "transientVisualSymptoms", "scalpTenderness"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Musculoskeletal chest pain",
    supportive: [
      "chestPain",
      "reproducibleChestWallTenderness",
      "movementRelatedChestPain",
      "postLiftingOnset",
    ],
    conflicting: [
      "hypoxia",
      "tachycardia",
      "collapse",
      "haemoptysis",
      "jawPain",
      "armPain",
      "sweating",
    ],
    expectedImportant: ["reproducibleChestWallTenderness", "movementRelatedChestPain"],
    supportiveWeights: {
      reproducibleChestWallTenderness: 5,
      movementRelatedChestPain: 4,
      postLiftingOnset: 3,
      chestPain: 1,
    },
    conflictingWeights: {
      hypoxia: 3,
      tachycardia: 2,
      collapse: 3,
      haemoptysis: 4,
      jawPain: 3,
      armPain: 3,
      sweating: 2,
    },
    strongSignatureGate: {
      features: ["reproducibleChestWallTenderness", "movementRelatedChestPain", "postLiftingOnset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Heart failure",
    supportive: ["sob", "orthopnoea", "ankleSwelling", "hypoxia", "tachypnoea"],
    conflicting: ["pleuriticPain", "suddenOnset", "fever", "haemoptysis"],
    expectedImportant: ["sob", "orthopnoea", "ankleSwelling"],
    supportiveWeights: {
      sob: 2,
      orthopnoea: 5,
      ankleSwelling: 4,
      hypoxia: 2,
      tachypnoea: 1,
    },
    conflictingWeights: {
      pleuriticPain: 3,
      suddenOnset: 2,
      fever: 2,
      haemoptysis: 3,
    },
    strongSignatureGate: {
      features: ["sob", "orthopnoea", "ankleSwelling"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Panic / anxiety",
    supportive: ["chestPain", "sob", "tachypnoea", "panicFeatures"],
    conflicting: [
      "hypoxia",
      "hypotension",
      "fever",
      "focalNeurology",
      "pleuriticPain",
      "unilateralReducedAirEntry",
    ],
    expectedImportant: ["panicFeatures", "sob"],
    supportiveWeights: {
      chestPain: 1,
      sob: 1,
      tachypnoea: 1,
      panicFeatures: 5,
    },
    conflictingWeights: {
      hypoxia: 4,
      hypotension: 4,
      fever: 2,
      focalNeurology: 4,
      pleuriticPain: 2,
      unilateralReducedAirEntry: 4,
    },
    strongSignatureGate: {
      features: ["panicFeatures"],
      threshold: 1,
      cappedScore: 1,
    },
  },
  {
    name: "Asthma exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "knownAsthma",
      "recentInfection",
      "increasedInhalerUse",
      "difficultySpeaking",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["haemoptysis", "pleuriticPain", "unilateralReducedAirEntry"],
    expectedImportant: ["sob", "wheeze", "knownAsthma"],
    supportiveWeights: {
      sob: 3,
      wheeze: 4,
      knownAsthma: 3,
      recentInfection: 1,
      increasedInhalerUse: 3,
      difficultySpeaking: 4,
      hypoxia: 2,
      tachypnoea: 2,
    },
    conflictingWeights: {
      haemoptysis: 4,
      pleuriticPain: 2,
      unilateralReducedAirEntry: 3,
    },
    strongSignatureGate: {
      features: ["sob", "wheeze", "knownAsthma", "increasedInhalerUse", "difficultySpeaking"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "COPD exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "knownCopd",
      "sputumChange",
      "productiveCough",
      "progressiveCourse",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["chestPain", "haemoptysis"],
    expectedImportant: ["sob", "knownCopd", "progressiveCourse"],
    supportiveWeights: {
      sob: 3,
      wheeze: 3,
      knownCopd: 4,
      sputumChange: 3,
      productiveCough: 2,
      progressiveCourse: 3,
      hypoxia: 2,
      tachypnoea: 2,
    },
    strongSignatureGate: {
      features: ["sob", "knownCopd", "progressiveCourse", "sputumChange"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Appendicitis",
    supportive: [
      "abdominalPain",
      "rifPain",
      "migrationToRIF",
      "rifTenderness",
      "anorexia",
      "fever",
      "nausea",
      "vomiting",
      "abdominalMovementPain",
      "guardingRigidity",
    ],
    conflicting: ["diarrhoea", "painOutOfProportion", "vaginalBleeding", "pregnancyPossible"],
    expectedImportant: ["rifPain", "migrationToRIF"],
    supportiveWeights: {
      abdominalPain: 0,
      rifPain: 6,
      migrationToRIF: 7,
      rifTenderness: 5,
      anorexia: 2,
      fever: 2,
      nausea: 0,
      vomiting: 0,
      abdominalMovementPain: 2,
      guardingRigidity: 3,
    },
    conflictingWeights: {
      diarrhoea: 1,
      painOutOfProportion: 3,
      vaginalBleeding: 3,
      pregnancyPossible: 2,
    },
    strongSignatureGate: {
      features: ["rifPain", "migrationToRIF", "rifTenderness", "anorexia", "abdominalMovementPain", "guardingRigidity"],
      threshold: 2,
      cappedScore: 4,
    },
  },
  {
    name: "Ectopic pregnancy",
    supportive: ["abdominalPain", "pelvicPain", "pregnancyPossible", "missedPeriod", "vaginalBleeding", "collapse", "hypotension", "recentMiscarriage"],
    conflicting: ["diarrhoea", "painOutOfProportion"],
    expectedImportant: ["pregnancyPossible", "missedPeriod", "vaginalBleeding"],
    supportiveWeights: {
      abdominalPain: 1,
      pelvicPain: 3,
      pregnancyPossible: 5,
      missedPeriod: 4,
      vaginalBleeding: 5,
      collapse: 3,
      hypotension: 2,
      recentMiscarriage: 3,
    },
    strongSignatureGate: {
      features: ["pregnancyPossible", "missedPeriod", "vaginalBleeding", "collapse"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Ovarian / acute pelvic pathology",
    supportive: ["abdominalPain", "pelvicPain", "suddenOnset", "vomiting", "vaginalBleeding"],
    conflicting: ["diarrhoea", "painOutOfProportion"],
    expectedImportant: ["pelvicPain", "suddenOnset"],
    supportiveWeights: {
      abdominalPain: 1,
      pelvicPain: 4,
      suddenOnset: 2,
      vomiting: 1,
      vaginalBleeding: 2,
    },
    strongSignatureGate: {
      features: ["pelvicPain", "vaginalBleeding"],
      threshold: 1,
      cappedScore: 1,
    },
  },
  {
    name: "Testicular torsion",
    supportive: ["unilateralTesticularPain", "suddenOnset", "vomiting", "abdominalPain"],
    conflicting: ["fever", "urinarySymptoms"],
    expectedImportant: ["unilateralTesticularPain", "suddenOnset"],
    supportiveWeights: {
      unilateralTesticularPain: 7,
      suddenOnset: 3,
      vomiting: 2,
      abdominalPain: 1,
    },
    strongSignatureGate: {
      features: ["unilateralTesticularPain"],
      threshold: 1,
      cappedScore: 2,
    },
  },
  {
    name: "Cauda equina syndrome",
    supportive: ["backPain", "urinaryRetention", "saddleNumbness", "bilateralLegSymptoms"],
    conflicting: ["fever", "headache", "chestPain"],
    expectedImportant: ["urinaryRetention", "saddleNumbness", "bilateralLegSymptoms"],
    supportiveWeights: {
      backPain: 1,
      urinaryRetention: 6,
      saddleNumbness: 6,
      bilateralLegSymptoms: 5,
    },
    strongSignatureGate: {
      features: ["urinaryRetention", "saddleNumbness", "bilateralLegSymptoms"],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "TIA",
    supportive: ["focalNeurology", "transientFocalDeficit", "suddenOnset"],
    conflicting: ["thunderclap", "headache", "neckStiffness", "fever", "gradualSpreadPositiveSymptoms"],
    expectedImportant: ["focalNeurology", "transientFocalDeficit"],
    supportiveWeights: {
      focalNeurology: 3,
      transientFocalDeficit: 6,
      suddenOnset: 2,
    },
    conflictingWeights: {
      thunderclap: 4,
      headache: 2,
      neckStiffness: 3,
      fever: 2,
      gradualSpreadPositiveSymptoms: 4,
    },
    strongSignatureGate: {
      features: ["focalNeurology", "transientFocalDeficit"],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "Hypoglycaemia",
    supportive: ["confusion", "collapse", "sweating", "diabeticContext", "hypoglycaemiaCue"],
    conflicting: ["fever", "focalNeurology", "thunderclap"],
    expectedImportant: ["diabeticContext", "hypoglycaemiaCue"],
    supportiveWeights: {
      confusion: 2,
      collapse: 2,
      sweating: 2,
      diabeticContext: 4,
      hypoglycaemiaCue: 5,
    },
    strongSignatureGate: {
      features: ["diabeticContext", "hypoglycaemiaCue", "sweating", "confusion"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "UTI / urosepsis",
    supportive: ["fever", "urinarySymptoms", "flankPain", "confusion", "rigors", "hypotension", "infectionSource"],
    conflicting: ["headache", "neckStiffness", "thunderclap"],
    expectedImportant: ["urinarySymptoms", "fever"],
    supportiveWeights: {
      fever: 2,
      urinarySymptoms: 5,
      flankPain: 3,
      confusion: 2,
      rigors: 2,
      hypotension: 2,
      infectionSource: 2,
    },
    strongSignatureGate: {
      features: ["urinarySymptoms", "flankPain"],
      threshold: 1,
      cappedScore: 1,
    },
  },
];

export function findDiagnosisRule(name: string): DiagnosisRule | undefined {
  const canonicalName = normaliseDiagnosisName(name);

  return DIAGNOSIS_RULES.find(
    (diagnosisRule) => diagnosisRule.name.toLowerCase() === canonicalName.toLowerCase(),
  );
}
