import type { FeatureWeightMap, SignatureGate } from "../types";
import { normaliseDiagnosisName } from "./diagnosisAliases";

export type DiagnosisRule = {
  name: string;
  supportive: string[];
  conflicting: string[];
  expectedImportant?: string[];
  supportiveWeights?: FeatureWeightMap;
  conflictingWeights?: FeatureWeightMap;
  strongSignatureGate?: SignatureGate;
};

export const DIAGNOSIS_RULES: DiagnosisRule[] = [
  {
    name: "Acute aortic syndrome",
    supportive: [
      "chest_pain",
      "sudden_onset",
      "tearing_pain",
      "back_radiation",
      "collapse",
      "hypertension",
    ],
    conflicting: ["fever"],
    expectedImportant: ["sudden_onset", "tearing_pain", "back_radiation"],
  },
  {
    name: "Abdominal aortic aneurysm",
    supportive: [
      "abdominal_pain",
      "back_radiation",
      "collapse",
      "pulsatile_abdomen",
      "smoker",
      "hypotension",
      "hypertension",
    ],
    conflicting: [],
    expectedImportant: ["collapse", "pulsatile_abdomen"],
  },
  {
    name: "Acute coronary syndrome",
    supportive: [
      "chest_pain",
      "jaw_pain",
      "arm_pain",
      "sweating",
      "nausea",
      "indigestion_like_chest_pain",
      "abdominal_pain",
      "collapse",
      "hypertension",
      "smoker",
      "sob",
    ],
    conflicting: [
      "tearing_pain",
      "pulsatile_abdomen",
      "back_radiation",
      "reproducible_chest_wall_tenderness",
      "movement_related_chest_pain",
      "post_lifting_onset",
    ],
    expectedImportant: ["chest_pain", "jaw_pain", "arm_pain", "sweating", "indigestion_like_chest_pain"],
    supportiveWeights: {
      chest_pain: 3,
      jaw_pain: 4,
      arm_pain: 4,
      sweating: 3,
      nausea: 2,
      indigestion_like_chest_pain: 4,
      abdominal_pain: 1,
      collapse: 2,
      hypertension: 1,
      smoker: 1,
      sob: 2,
    },
    conflictingWeights: {
      reproducible_chest_wall_tenderness: 4,
      movement_related_chest_pain: 3,
      post_lifting_onset: 3,
    },
    strongSignatureGate: {
      features: ["chest_pain", "jaw_pain", "arm_pain", "sweating", "indigestion_like_chest_pain"],
      threshold: 2,
      cappedScore: 6,
    },
  },
  {
    name: "Pulmonary embolism",
    supportive: [
      "chest_pain",
      "sob",
      "sudden_onset",
      "tachycardia",
      "tachypnoea",
      "collapse",
      "pleuritic_pain",
      "hypoxia",
      "haemoptysis",
      "recent_surgery",
      "immobility",
      "long_haul_travel",
    ],
    conflicting: [
      "pulsatile_abdomen",
      "tearing_pain",
      "back_radiation",
      "unilateral_reduced_air_entry",
      "tall_thin_habitus",
      "previous_pneumothorax",
      "recent_chest_drain",
      "reproducible_chest_wall_tenderness",
      "post_lifting_onset",
      "wheeze",
    ],
    expectedImportant: ["sob", "sudden_onset"],
    supportiveWeights: {
      chest_pain: 3,
      sudden_onset: 3,
      tachycardia: 3,
      tachypnoea: 3,
      sob: 3,
      pleuritic_pain: 3,
      hypoxia: 2,
      haemoptysis: 3,
      collapse: 3,
      recent_surgery: 2,
      immobility: 2,
      long_haul_travel: 2,
    },
    conflictingWeights: {
      unilateral_reduced_air_entry: 2,
      tall_thin_habitus: 1,
      previous_pneumothorax: 1,
      recent_chest_drain: 1,
      reproducible_chest_wall_tenderness: 3,
      post_lifting_onset: 3,
      wheeze: 2,
    },
    strongSignatureGate: {
      features: ["chest_pain", "sob", "sudden_onset", "pleuritic_pain", "hypoxia"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "GORD",
    supportive: [
      "chest_pain",
      "indigestion_like_chest_pain",
      "heartburn",
      "acid_regurgitation",
      "worse_after_meals",
      "worse_lying_flat",
      "antacid_relief",
    ],
    conflicting: [
      "sudden_onset",
      "tearing_pain",
      "back_radiation",
      "collapse",
      "pulsatile_abdomen",
      "hypotension",
    ],
    expectedImportant: ["indigestion_like_chest_pain", "heartburn", "acid_regurgitation"],
    supportiveWeights: {
      chest_pain: 1,
      indigestion_like_chest_pain: 2,
      heartburn: 4,
      acid_regurgitation: 3,
      worse_after_meals: 2,
      worse_lying_flat: 2,
      antacid_relief: 3,
    },
  },
  {
    name: "Mesenteric ischaemia",
    supportive: ["abdominal_pain", "pain_out_of_proportion", "af", "collapse", "vomiting", "hypotension"],
    conflicting: ["chest_pain", "diarrhoea"],
    expectedImportant: ["abdominal_pain", "pain_out_of_proportion"],
    supportiveWeights: {
      abdominal_pain: 1,
      pain_out_of_proportion: 7,
      af: 4,
      collapse: 3,
      hypotension: 3,
      vomiting: 0,
    },
    conflictingWeights: {
      chest_pain: 2,
      diarrhoea: 1,
    },
    strongSignatureGate: {
      features: ["abdominal_pain", "pain_out_of_proportion", "af", "collapse", "hypotension"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Acute pancreatitis",
    supportive: [
      "abdominal_pain",
      "back_radiation",
      "vomiting",
      "nausea",
      "alcohol_excess",
      "binge_drinking",
      "gallstone_context",
      "severe_constant_upper_abdominal_pain",
    ],
    conflicting: [
      "diarrhoea",
      "gi_bleed",
      "pr_bleeding",
      "melaena",
      "haematemesis",
      "localized_ruq_tenderness",
      "murphys_sign",
    ],
    expectedImportant: ["abdominal_pain", "vomiting", "back_radiation"],
    supportiveWeights: {
      abdominal_pain: 2,
      back_radiation: 3,
      vomiting: 2,
      nausea: 1,
      alcohol_excess: 2,
      binge_drinking: 2,
      gallstone_context: 2,
      severe_constant_upper_abdominal_pain: 3,
    },
    conflictingWeights: {
      diarrhoea: 2,
      gi_bleed: 3,
      pr_bleeding: 3,
      melaena: 3,
      haematemesis: 3,
      localized_ruq_tenderness: 2,
      murphys_sign: 3,
    },
    strongSignatureGate: {
      features: [
        "abdominal_pain",
        "back_radiation",
        "vomiting",
        "alcohol_excess",
        "binge_drinking",
        "gallstone_context",
        "severe_constant_upper_abdominal_pain",
      ],
      threshold: 3,
      cappedScore: 2,
    },
  },
  {
    name: "Perforated viscus",
    supportive: [
      "abdominal_pain",
      "sudden_onset",
      "guarding_rigidity",
      "abdominal_movement_pain",
      "perforation_language",
      "peptic_ulcer_disease",
      "collapse",
      "hypotension",
    ],
    conflicting: ["diarrhoea", "chest_pain"],
    expectedImportant: ["abdominal_pain", "sudden_onset", "guarding_rigidity"],
    supportiveWeights: {
      abdominal_pain: 1,
      sudden_onset: 3,
      guarding_rigidity: 6,
      abdominal_movement_pain: 4,
      perforation_language: 5,
      peptic_ulcer_disease: 2,
      collapse: 2,
      hypotension: 2,
    },
    conflictingWeights: {
      diarrhoea: 2,
      chest_pain: 2,
    },
    strongSignatureGate: {
      features: [
        "abdominal_pain",
        "sudden_onset",
        "guarding_rigidity",
        "abdominal_movement_pain",
        "perforation_language",
        "peptic_ulcer_disease",
      ],
      threshold: 2,
      cappedScore: 5,
    },
  },
  {
    name: "Subarachnoid haemorrhage",
    supportive: ["thunderclap", "headache", "vomiting", "neck_stiffness", "collapse", "focal_neurology"],
    conflicting: ["gradual_onset", "visual_aura", "gradual_spread_positive_symptoms", "well_intervals"],
    expectedImportant: ["thunderclap", "headache"],
    supportiveWeights: {
      thunderclap: 6,
      headache: 2,
      vomiting: 1,
      neck_stiffness: 2,
      collapse: 3,
      focal_neurology: 2,
    },
    conflictingWeights: {
      gradual_onset: 3,
      visual_aura: 3,
      gradual_spread_positive_symptoms: 4,
      well_intervals: 2,
    },
    strongSignatureGate: {
      features: ["thunderclap"],
      threshold: 1,
      cappedScore: 4,
    },
  },
  {
    name: "Stroke / neurological emergency",
    supportive: ["confusion", "focal_neurology", "collapse", "sudden_onset"],
    conflicting: [],
    expectedImportant: ["focal_neurology", "confusion"],
  },
  {
    name: "Delirium secondary to infection",
    supportive: ["confusion", "fever", "infection_source", "recent_infection", "fluctuation"],
    conflicting: ["focal_neurology", "thunderclap"],
    expectedImportant: ["confusion", "fluctuation"],
    supportiveWeights: {
      confusion: 4,
      fever: 2,
      infection_source: 3,
      recent_infection: 2,
      fluctuation: 3,
    },
  },
  {
    name: "Gastroenteritis",
    supportive: ["abdominal_pain", "diarrhoea", "vomiting", "fever"],
    conflicting: [
      "pain_out_of_proportion",
      "collapse",
      "af",
      "hypotension",
      "gi_bleed",
      "pr_bleeding",
      "ruq_pain",
      "persistent_ruq_pain",
      "localized_ruq_tenderness",
      "murphys_sign",
      "gallstone_context",
      "rif_pain",
      "migration_to_rif",
      "pregnancy_possible",
      "missed_period",
      "vaginal_bleeding",
      "unilateral_testicular_pain",
    ],
    expectedImportant: ["abdominal_pain", "diarrhoea"],
    conflictingWeights: {
      pain_out_of_proportion: 3,
      collapse: 3,
      hypotension: 3,
      gi_bleed: 4,
      pr_bleeding: 4,
      ruq_pain: 2,
      persistent_ruq_pain: 3,
      localized_ruq_tenderness: 3,
      murphys_sign: 4,
      gallstone_context: 2,
      rif_pain: 3,
      migration_to_rif: 4,
      pregnancy_possible: 3,
      missed_period: 3,
      vaginal_bleeding: 4,
      unilateral_testicular_pain: 5,
    },
  },
  {
    name: "Acute cholangitis",
    supportive: [
      "ruq_pain",
      "abdominal_pain",
      "jaundice",
      "fever",
      "rigors",
      "nausea",
      "vomiting",
      "dark_urine",
      "pale_stools",
      "obstructive_jaundice_language",
      "gallstone_context",
      "confusion",
      "hypotension",
      "tachycardia",
    ],
    conflicting: [
      "diarrhoea",
      "pruritus",
      "dry_eyes_mouth",
      "fatigue",
      "chronic_course",
      "murphys_sign",
      "post_prandial_pain",
      "recurrent_biliary_pain",
    ],
    expectedImportant: ["ruq_pain", "jaundice", "fever"],
    supportiveWeights: {
      ruq_pain: 4,
      abdominal_pain: 1,
      jaundice: 4,
      fever: 3,
      rigors: 4,
      nausea: 1,
      vomiting: 1,
      dark_urine: 2,
      pale_stools: 2,
      obstructive_jaundice_language: 3,
      gallstone_context: 2,
      confusion: 1,
      hypotension: 2,
      tachycardia: 1,
    },
    conflictingWeights: {
      diarrhoea: 2,
      pruritus: 2,
      dry_eyes_mouth: 3,
      fatigue: 2,
      chronic_course: 4,
      murphys_sign: 3,
      post_prandial_pain: 3,
      recurrent_biliary_pain: 3,
    },
    strongSignatureGate: {
      features: [
        "ruq_pain",
        "jaundice",
        "fever",
        "rigors",
      ],
      threshold: 3,
      cappedScore: 0,
    },
  },
  {
    name: "Acute cholecystitis",
    supportive: [
      "ruq_pain",
      "abdominal_pain",
      "persistent_ruq_pain",
      "localized_ruq_tenderness",
      "murphys_sign",
      "fever",
      "nausea",
      "vomiting",
      "post_prandial_pain",
      "gallstone_context",
    ],
    conflicting: [
      "jaundice",
      "dark_urine",
      "pale_stools",
      "obstructive_jaundice_language",
      "rigors",
      "hypotension",
      "confusion",
      "well_between_episodes",
    ],
    expectedImportant: ["ruq_pain", "persistent_ruq_pain", "murphys_sign"],
    supportiveWeights: {
      ruq_pain: 4,
      abdominal_pain: 1,
      persistent_ruq_pain: 6,
      localized_ruq_tenderness: 6,
      murphys_sign: 6,
      fever: 4,
      nausea: 2,
      vomiting: 2,
      post_prandial_pain: 3,
      gallstone_context: 3,
    },
    conflictingWeights: {
      jaundice: 2,
      dark_urine: 2,
      pale_stools: 2,
      obstructive_jaundice_language: 3,
      rigors: 2,
      hypotension: 2,
      confusion: 2,
      well_between_episodes: 3,
    },
    strongSignatureGate: {
      features: [
        "ruq_pain",
        "persistent_ruq_pain",
        "localized_ruq_tenderness",
        "murphys_sign",
        "fever",
        "gallstone_context",
      ],
      threshold: 3,
      cappedScore: 1,
    },
  },
  {
    name: "Choledocholithiasis / obstructive jaundice",
    supportive: [
      "jaundice",
      "dark_urine",
      "pale_stools",
      "pruritus",
      "obstructive_jaundice_language",
      "gallstone_context",
      "ruq_pain",
      "abdominal_pain",
    ],
    conflicting: [
      "fever",
      "rigors",
      "hypotension",
      "confusion",
      "chronic_course",
      "dry_eyes_mouth",
      "ibd_context",
    ],
    expectedImportant: ["jaundice", "dark_urine", "pale_stools"],
    supportiveWeights: {
      jaundice: 5,
      dark_urine: 3,
      pale_stools: 3,
      pruritus: 2,
      obstructive_jaundice_language: 5,
      gallstone_context: 2,
      ruq_pain: 1,
      abdominal_pain: 1,
    },
    conflictingWeights: {
      fever: 2,
      rigors: 3,
      hypotension: 2,
      confusion: 2,
      chronic_course: 1,
      dry_eyes_mouth: 2,
      ibd_context: 2,
    },
    strongSignatureGate: {
      features: [
        "jaundice",
        "dark_urine",
        "pale_stools",
        "pruritus",
        "obstructive_jaundice_language",
        "gallstone_context",
      ],
      threshold: 3,
      cappedScore: 1,
    },
  },
  {
    name: "Biliary colic / gallstone disease",
    supportive: [
      "ruq_pain",
      "abdominal_pain",
      "post_prandial_pain",
      "recurrent_biliary_pain",
      "well_between_episodes",
      "gallstone_context",
      "nausea",
    ],
    conflicting: [
      "fever",
      "jaundice",
      "dark_urine",
      "pale_stools",
      "rigors",
      "hypotension",
      "confusion",
      "persistent_ruq_pain",
      "localized_ruq_tenderness",
      "murphys_sign",
    ],
    expectedImportant: ["ruq_pain", "post_prandial_pain", "well_between_episodes"],
    supportiveWeights: {
      ruq_pain: 3,
      abdominal_pain: 1,
      post_prandial_pain: 4,
      recurrent_biliary_pain: 4,
      well_between_episodes: 4,
      gallstone_context: 3,
      nausea: 1,
    },
    conflictingWeights: {
      fever: 3,
      jaundice: 3,
      dark_urine: 2,
      pale_stools: 2,
      rigors: 3,
      hypotension: 2,
      confusion: 2,
      persistent_ruq_pain: 3,
      localized_ruq_tenderness: 2,
      murphys_sign: 3,
    },
    strongSignatureGate: {
      features: [
        "ruq_pain",
        "post_prandial_pain",
        "recurrent_biliary_pain",
        "well_between_episodes",
        "gallstone_context",
      ],
      threshold: 3,
      cappedScore: 0,
    },
  },
  {
    name: "Pneumonia",
    supportive: [
      "sob",
      "fever",
      "pleuritic_pain",
      "hypoxia",
      "productive_cough",
      "infection_source",
      "rigors",
      "progressive_course",
      "sputum_change",
    ],
    conflicting: ["sudden_onset", "collapse"],
    expectedImportant: ["sob", "fever", "productive_cough"],
    supportiveWeights: {
      productive_cough: 3,
      infection_source: 2,
      rigors: 2,
      progressive_course: 3,
      sputum_change: 2,
      fever: 3,
      sob: 2,
      pleuritic_pain: 2,
      hypoxia: 2,
    },
    conflictingWeights: {
      sudden_onset: 3,
      collapse: 3,
    },
  },
  {
    name: "Pneumothorax",
    supportive: [
      "chest_pain",
      "sob",
      "pleuritic_pain",
      "hypoxia",
      "sudden_onset",
      "unilateral_reduced_air_entry",
      "tall_thin_habitus",
      "recent_chest_drain",
      "previous_pneumothorax",
      "trauma",
      "smoker",
    ],
    conflicting: ["fever"],
    expectedImportant: ["sudden_onset", "sob", "pleuritic_pain"],
    supportiveWeights: {
      sudden_onset: 4,
      hypoxia: 1,
      chest_pain: 1,
      sob: 4,
      pleuritic_pain: 5,
      unilateral_reduced_air_entry: 10,
      tall_thin_habitus: 5,
      recent_chest_drain: 3,
      previous_pneumothorax: 3,
      trauma: 3,
      smoker: 2,
    },
    strongSignatureGate: {
      features: [
        "pleuritic_pain",
        "unilateral_reduced_air_entry",
        "trauma",
        "tall_thin_habitus",
        "previous_pneumothorax",
      ],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Migraine",
    supportive: [
      "headache",
      "vomiting",
      "photophobia",
      "nausea",
      "visual_aura",
      "throbbing_headache",
      "unilateral_headache",
      "recurrent_headache",
      "well_intervals",
    ],
    conflicting: ["thunderclap", "focal_neurology", "neck_stiffness", "fever", "collapse"],
    expectedImportant: ["headache", "photophobia", "visual_aura"],
    supportiveWeights: {
      headache: 2,
      photophobia: 3,
      nausea: 2,
      visual_aura: 4,
      throbbing_headache: 3,
      unilateral_headache: 2,
      recurrent_headache: 2,
      well_intervals: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focal_neurology: 4,
      neck_stiffness: 3,
      fever: 2,
      collapse: 3,
    },
    strongSignatureGate: {
      features: [
        "headache",
        "photophobia",
        "visual_aura",
        "throbbing_headache",
        "unilateral_headache",
        "recurrent_headache",
      ],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "Tension headache",
    supportive: [
      "headache",
      "gradual_onset",
      "bilateral_headache",
      "band_like_headache",
      "stress_trigger",
      "poor_sleep",
    ],
    conflicting: [
      "thunderclap",
      "focal_neurology",
      "neck_stiffness",
      "fever",
      "photophobia",
      "vomiting",
      "visual_aura",
    ],
    expectedImportant: ["headache", "bilateral_headache", "band_like_headache"],
    supportiveWeights: {
      headache: 2,
      gradual_onset: 2,
      bilateral_headache: 3,
      band_like_headache: 4,
      stress_trigger: 2,
      poor_sleep: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focal_neurology: 4,
      neck_stiffness: 3,
      fever: 2,
      photophobia: 2,
      vomiting: 2,
      visual_aura: 3,
    },
    strongSignatureGate: {
      features: ["headache", "bilateral_headache", "band_like_headache", "gradual_onset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Meningitis / encephalitis",
    supportive: [
      "confusion",
      "fever",
      "headache",
      "neck_stiffness",
      "vomiting",
      "photophobia",
      "shared_accommodation",
      "recent_infection",
    ],
    conflicting: [
      "ruq_pain",
      "persistent_ruq_pain",
      "localized_ruq_tenderness",
      "murphys_sign",
      "post_prandial_pain",
      "gallstone_context",
    ],
    expectedImportant: ["fever", "headache", "neck_stiffness"],
    supportiveWeights: {
      neck_stiffness: 3,
      confusion: 3,
      photophobia: 3,
      shared_accommodation: 1,
      recent_infection: 1,
    },
    conflictingWeights: {
      ruq_pain: 2,
      persistent_ruq_pain: 3,
      localized_ruq_tenderness: 3,
      murphys_sign: 4,
      post_prandial_pain: 2,
      gallstone_context: 2,
    },
  },
  {
    name: "GI bleed",
    supportive: [
      "gi_bleed",
      "pr_bleeding",
      "melaena",
      "haematemesis",
      "collapse",
      "hypotension",
      "tachycardia",
      "vomiting",
      "abdominal_pain",
      "alcohol_excess",
      "binge_drinking",
      "peptic_ulcer_disease",
      "nsaid_use",
    ],
    conflicting: ["diarrhoea"],
    expectedImportant: ["gi_bleed", "hypotension"],
    supportiveWeights: {
      gi_bleed: 4,
      pr_bleeding: 3,
      melaena: 3,
      haematemesis: 3,
      hypotension: 1,
      collapse: 2,
      tachycardia: 1,
      vomiting: 1,
      abdominal_pain: 1,
      alcohol_excess: 1,
      binge_drinking: 1,
      peptic_ulcer_disease: 2,
      nsaid_use: 2,
    },
    strongSignatureGate: {
      features: ["gi_bleed", "pr_bleeding", "melaena", "haematemesis"],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Sepsis",
    supportive: [
      "fever",
      "hypothermia",
      "rigors",
      "infection_source",
      "hypotension",
      "tachycardia",
      "tachypnoea",
      "confusion",
      "sob",
      "collapse",
    ],
    conflicting: [],
    expectedImportant: ["fever", "hypotension", "tachycardia"],
    supportiveWeights: {
      fever: 3,
      hypothermia: 3,
      rigors: 3,
      infection_source: 3,
      hypotension: 1,
      tachycardia: 1,
      tachypnoea: 1,
      confusion: 3,
      sob: 1,
      collapse: 1,
    },
    strongSignatureGate: {
      features: ["fever", "hypothermia", "rigors", "infection_source"],
      threshold: 1,
      cappedScore: 3,
    },
  },
  {
    name: "Viral illness",
    supportive: ["fever", "headache", "vomiting"],
    conflicting: ["hypotension", "collapse", "confusion"],
    expectedImportant: ["fever"],
    conflictingWeights: {
      hypotension: 4,
      collapse: 3,
      confusion: 3,
    },
  },
  {
    name: "Temporal arteritis",
    supportive: [
      "headache",
      "temporal_headache",
      "scalp_tenderness",
      "jaw_claudication",
      "transient_visual_symptoms",
      "pmr_like_symptoms",
    ],
    conflicting: ["thunderclap", "vomiting", "focal_neurology"],
    expectedImportant: ["temporal_headache", "jaw_claudication", "transient_visual_symptoms"],
    supportiveWeights: {
      temporal_headache: 3,
      scalp_tenderness: 3,
      jaw_claudication: 5,
      transient_visual_symptoms: 4,
      pmr_like_symptoms: 3,
      headache: 1,
    },
    strongSignatureGate: {
      features: ["temporal_headache", "jaw_claudication", "transient_visual_symptoms", "scalp_tenderness"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Musculoskeletal chest pain",
    supportive: [
      "chest_pain",
      "reproducible_chest_wall_tenderness",
      "movement_related_chest_pain",
      "post_lifting_onset",
    ],
    conflicting: [
      "hypoxia",
      "tachycardia",
      "collapse",
      "haemoptysis",
      "jaw_pain",
      "arm_pain",
      "sweating",
    ],
    expectedImportant: ["reproducible_chest_wall_tenderness", "movement_related_chest_pain"],
    supportiveWeights: {
      reproducible_chest_wall_tenderness: 5,
      movement_related_chest_pain: 4,
      post_lifting_onset: 3,
      chest_pain: 1,
    },
    conflictingWeights: {
      hypoxia: 3,
      tachycardia: 2,
      collapse: 3,
      haemoptysis: 4,
      jaw_pain: 3,
      arm_pain: 3,
      sweating: 2,
    },
    strongSignatureGate: {
      features: ["reproducible_chest_wall_tenderness", "movement_related_chest_pain", "post_lifting_onset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Heart failure",
    supportive: ["sob", "orthopnoea", "ankle_swelling", "hypoxia", "tachypnoea"],
    conflicting: ["pleuritic_pain", "sudden_onset", "fever", "haemoptysis"],
    expectedImportant: ["sob", "orthopnoea", "ankle_swelling"],
    supportiveWeights: {
      sob: 2,
      orthopnoea: 5,
      ankle_swelling: 4,
      hypoxia: 2,
      tachypnoea: 1,
    },
    conflictingWeights: {
      pleuritic_pain: 3,
      sudden_onset: 2,
      fever: 2,
      haemoptysis: 3,
    },
    strongSignatureGate: {
      features: ["sob", "orthopnoea", "ankle_swelling"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Panic / anxiety",
    supportive: ["chest_pain", "sob", "tachypnoea", "panic_features"],
    conflicting: [
      "hypoxia",
      "hypotension",
      "fever",
      "focal_neurology",
      "pleuritic_pain",
      "unilateral_reduced_air_entry",
    ],
    expectedImportant: ["panic_features", "sob"],
    supportiveWeights: {
      chest_pain: 1,
      sob: 1,
      tachypnoea: 1,
      panic_features: 5,
    },
    conflictingWeights: {
      hypoxia: 4,
      hypotension: 4,
      fever: 2,
      focal_neurology: 4,
      pleuritic_pain: 2,
      unilateral_reduced_air_entry: 4,
    },
    strongSignatureGate: {
      features: ["panic_features"],
      threshold: 1,
      cappedScore: 1,
    },
  },
  {
    name: "Asthma exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "known_asthma",
      "recent_infection",
      "increased_inhaler_use",
      "difficulty_speaking",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["haemoptysis", "pleuritic_pain", "unilateral_reduced_air_entry"],
    expectedImportant: ["sob", "wheeze", "known_asthma"],
    supportiveWeights: {
      sob: 3,
      wheeze: 4,
      known_asthma: 3,
      recent_infection: 1,
      increased_inhaler_use: 3,
      difficulty_speaking: 4,
      hypoxia: 2,
      tachypnoea: 2,
    },
    conflictingWeights: {
      haemoptysis: 4,
      pleuritic_pain: 2,
      unilateral_reduced_air_entry: 3,
    },
    strongSignatureGate: {
      features: ["sob", "wheeze", "known_asthma", "increased_inhaler_use", "difficulty_speaking"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "COPD exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "known_copd",
      "sputum_change",
      "productive_cough",
      "progressive_course",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["chest_pain", "haemoptysis"],
    expectedImportant: ["sob", "known_copd", "progressive_course"],
    supportiveWeights: {
      sob: 3,
      wheeze: 3,
      known_copd: 4,
      sputum_change: 3,
      productive_cough: 2,
      progressive_course: 3,
      hypoxia: 2,
      tachypnoea: 2,
    },
    strongSignatureGate: {
      features: ["sob", "known_copd", "progressive_course", "sputum_change"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Appendicitis",
    supportive: [
      "abdominal_pain",
      "rif_pain",
      "migration_to_rif",
      "rif_tenderness",
      "anorexia",
      "fever",
      "nausea",
      "vomiting",
      "abdominal_movement_pain",
      "guarding_rigidity",
    ],
    conflicting: ["diarrhoea", "pain_out_of_proportion", "vaginal_bleeding", "pregnancy_possible"],
    expectedImportant: ["rif_pain", "migration_to_rif"],
    supportiveWeights: {
      abdominal_pain: 0,
      rif_pain: 6,
      migration_to_rif: 7,
      rif_tenderness: 5,
      anorexia: 2,
      fever: 2,
      nausea: 0,
      vomiting: 0,
      abdominal_movement_pain: 2,
      guarding_rigidity: 3,
    },
    conflictingWeights: {
      diarrhoea: 1,
      pain_out_of_proportion: 3,
      vaginal_bleeding: 3,
      pregnancy_possible: 2,
    },
    strongSignatureGate: {
      features: ["rif_pain", "migration_to_rif", "rif_tenderness", "anorexia", "abdominal_movement_pain", "guarding_rigidity"],
      threshold: 2,
      cappedScore: 4,
    },
  },
  {
    name: "Ectopic pregnancy",
    supportive: ["abdominal_pain", "pelvic_pain", "pregnancy_possible", "missed_period", "vaginal_bleeding", "collapse", "hypotension", "recent_miscarriage"],
    conflicting: ["diarrhoea", "pain_out_of_proportion"],
    expectedImportant: ["pregnancy_possible", "missed_period", "vaginal_bleeding"],
    supportiveWeights: {
      abdominal_pain: 1,
      pelvic_pain: 3,
      pregnancy_possible: 5,
      missed_period: 4,
      vaginal_bleeding: 5,
      collapse: 3,
      hypotension: 2,
      recent_miscarriage: 3,
    },
    strongSignatureGate: {
      features: ["pregnancy_possible", "missed_period", "vaginal_bleeding", "collapse"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Ovarian / acute pelvic pathology",
    supportive: ["abdominal_pain", "pelvic_pain", "sudden_onset", "vomiting", "vaginal_bleeding"],
    conflicting: ["diarrhoea", "pain_out_of_proportion"],
    expectedImportant: ["pelvic_pain", "sudden_onset"],
    supportiveWeights: {
      abdominal_pain: 1,
      pelvic_pain: 4,
      sudden_onset: 2,
      vomiting: 1,
      vaginal_bleeding: 2,
    },
    strongSignatureGate: {
      features: ["pelvic_pain", "vaginal_bleeding"],
      threshold: 1,
      cappedScore: 1,
    },
  },
  {
    name: "Testicular torsion",
    supportive: ["unilateral_testicular_pain", "sudden_onset", "vomiting", "abdominal_pain"],
    conflicting: ["fever", "urinary_symptoms"],
    expectedImportant: ["unilateral_testicular_pain", "sudden_onset"],
    supportiveWeights: {
      unilateral_testicular_pain: 7,
      sudden_onset: 3,
      vomiting: 2,
      abdominal_pain: 1,
    },
    strongSignatureGate: {
      features: ["unilateral_testicular_pain"],
      threshold: 1,
      cappedScore: 2,
    },
  },
  {
    name: "Cauda equina syndrome",
    supportive: ["back_pain", "urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
    conflicting: ["fever", "headache", "chest_pain"],
    expectedImportant: ["urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
    supportiveWeights: {
      back_pain: 1,
      urinary_retention: 6,
      saddle_numbness: 6,
      bilateral_leg_symptoms: 5,
    },
    strongSignatureGate: {
      features: ["urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "TIA",
    supportive: ["focal_neurology", "transient_focal_deficit", "sudden_onset"],
    conflicting: ["thunderclap", "headache", "neck_stiffness", "fever", "gradual_spread_positive_symptoms"],
    expectedImportant: ["focal_neurology", "transient_focal_deficit"],
    supportiveWeights: {
      focal_neurology: 3,
      transient_focal_deficit: 6,
      sudden_onset: 2,
    },
    conflictingWeights: {
      thunderclap: 4,
      headache: 2,
      neck_stiffness: 3,
      fever: 2,
      gradual_spread_positive_symptoms: 4,
    },
    strongSignatureGate: {
      features: ["focal_neurology", "transient_focal_deficit"],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "Hypoglycaemia",
    supportive: ["confusion", "collapse", "sweating", "diabetic_context", "hypoglycaemia_cue"],
    conflicting: ["fever", "focal_neurology", "thunderclap"],
    expectedImportant: ["diabetic_context", "hypoglycaemia_cue"],
    supportiveWeights: {
      confusion: 2,
      collapse: 2,
      sweating: 2,
      diabetic_context: 4,
      hypoglycaemia_cue: 5,
    },
    strongSignatureGate: {
      features: ["diabetic_context", "hypoglycaemia_cue", "sweating", "confusion"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "UTI / urosepsis",
    supportive: ["fever", "urinary_symptoms", "flank_pain", "confusion", "rigors", "hypotension", "infection_source"],
    conflicting: ["headache", "neck_stiffness", "thunderclap"],
    expectedImportant: ["urinary_symptoms", "fever"],
    supportiveWeights: {
      fever: 2,
      urinary_symptoms: 5,
      flank_pain: 3,
      confusion: 2,
      rigors: 2,
      hypotension: 2,
      infection_source: 2,
    },
    strongSignatureGate: {
      features: ["urinary_symptoms", "flank_pain"],
      threshold: 1,
      cappedScore: 1,
    },
  },
];

export function findDiagnosisRule(name: string): DiagnosisRule | undefined {
  const canonicalName = normaliseDiagnosisName(name);

  return DIAGNOSIS_RULES.find(
    (diagnosisRule) => diagnosisRule.name.toLowerCase() === canonicalName.toLowerCase(),
  );
}
