import type { DiagnosisBoost, ExtractedFeatures } from "../types";

type DiagnosisBoostRule = {
  diagnosis: string;
  threshold: number;
  points: number;
  reason: string;
  features: string[];
  requiredAnyFeatures?: string[];
};

const DIAGNOSIS_BOOST_RULES: DiagnosisBoostRule[] = [
  {
    diagnosis: "Acute aortic syndrome",
    threshold: 3,
    points: 5,
    reason: "vascular catastrophe pattern",
    features: [
      "chestPain",
      "suddenOnset",
      "tearingPain",
      "backRadiation",
      "collapse",
      "hypertension",
    ],
  },
  {
    diagnosis: "Abdominal aortic aneurysm",
    threshold: 3,
    points: 5,
    reason: "AAA pattern",
    features: [
      "abdominalPain",
      "backRadiation",
      "collapse",
      "pulsatileAbdomen",
      "smoker",
      "hypotension",
      "hypertension",
    ],
  },
  {
    diagnosis: "Subarachnoid haemorrhage",
    threshold: 2,
    points: 7,
    reason: "sudden severe headache pattern",
    features: ["thunderclap", "headache", "vomiting", "neckStiffness", "collapse", "focalNeurology"],
    requiredAnyFeatures: ["thunderclap"],
  },
  {
    diagnosis: "Stroke / neurological emergency",
    threshold: 2,
    points: 4,
    reason: "neurological emergency pattern",
    features: ["confusion", "focalNeurology", "collapse"],
  },
  {
    diagnosis: "TIA",
    threshold: 2,
    points: 6,
    reason: "transient focal neurological pattern",
    features: ["focalNeurology", "transientFocalDeficit", "suddenOnset"],
    requiredAnyFeatures: ["transientFocalDeficit"],
  },
  {
    diagnosis: "Mesenteric ischaemia",
    threshold: 2,
    points: 9,
    reason: "mesenteric ischaemia pattern",
    features: ["abdominalPain", "painOutOfProportion", "af", "collapse", "hypotension"],
    requiredAnyFeatures: ["painOutOfProportion"],
  },
  {
    diagnosis: "Acute pancreatitis",
    threshold: 3,
    points: 5,
    reason: "pancreatitis pattern",
    features: [
      "abdominalPain",
      "backRadiation",
      "vomiting",
      "nausea",
      "alcoholExcess",
      "bingeDrinking",
      "gallstoneContext",
      "severeConstantUpperAbdominalPain",
    ],
    requiredAnyFeatures: ["backRadiation", "vomiting", "alcoholExcess", "bingeDrinking", "gallstoneContext"],
  },
  {
    diagnosis: "Perforated viscus",
    threshold: 3,
    points: 8,
    reason: "perforated viscus pattern",
    features: [
      "abdominalPain",
      "suddenOnset",
      "guardingRigidity",
      "abdominalMovementPain",
      "lyingStill",
      "perforationLanguage",
      "pepticUlcerDisease",
      "collapse",
      "hypotension",
    ],
    requiredAnyFeatures: ["guardingRigidity", "abdominalMovementPain", "lyingStill", "perforationLanguage"],
  },
  {
    diagnosis: "Appendicitis",
    threshold: 4,
    points: 8,
    reason: "appendicitis pattern",
    features: [
      "abdominalPain",
      "rifPain",
      "migrationToRIF",
      "rifTenderness",
      "anorexia",
      "fever",
      "nausea",
      "vomiting",
      "abdominalMovementPain",
    ],
    requiredAnyFeatures: ["rifPain", "migrationToRIF", "rifTenderness"],
  },
  {
    diagnosis: "Ectopic pregnancy",
    threshold: 4,
    points: 7,
    reason: "ectopic pregnancy pattern",
    features: ["abdominalPain", "pelvicPain", "pregnancyPossible", "missedPeriod", "vaginalBleeding", "collapse", "hypotension"],
    requiredAnyFeatures: ["pregnancyPossible", "missedPeriod", "vaginalBleeding"],
  },
  {
    diagnosis: "Ovarian / acute pelvic pathology",
    threshold: 3,
    points: 5,
    reason: "acute pelvic pathology pattern",
    features: ["abdominalPain", "pelvicPain", "suddenOnset", "vomiting", "vaginalBleeding"],
    requiredAnyFeatures: ["pelvicPain", "vaginalBleeding"],
  },
  {
    diagnosis: "Testicular torsion",
    threshold: 2,
    points: 8,
    reason: "testicular torsion pattern",
    features: ["unilateralTesticularPain", "suddenOnset", "vomiting", "abdominalPain"],
    requiredAnyFeatures: ["unilateralTesticularPain"],
  },
  {
    diagnosis: "Cauda equina syndrome",
    threshold: 2,
    points: 8,
    reason: "cauda equina pattern",
    features: ["backPain", "urinaryRetention", "saddleNumbness", "bilateralLegSymptoms"],
    requiredAnyFeatures: ["urinaryRetention", "saddleNumbness", "bilateralLegSymptoms"],
  },
  {
    diagnosis: "Hypoglycaemia",
    threshold: 3,
    points: 6,
    reason: "hypoglycaemia pattern",
    features: ["confusion", "collapse", "sweating", "diabeticContext", "hypoglycaemiaCue"],
    requiredAnyFeatures: ["diabeticContext", "hypoglycaemiaCue"],
  },
  {
    diagnosis: "UTI / urosepsis",
    threshold: 3,
    points: 5,
    reason: "urinary sepsis pattern",
    features: ["urinarySymptoms", "flankPain", "fever", "rigors", "confusion", "hypotension"],
    requiredAnyFeatures: ["urinarySymptoms", "flankPain"],
  },
  {
    diagnosis: "Acute cholangitis",
    threshold: 4,
    points: 6,
    reason: "acute cholangitis pattern",
    features: [
      "ruqPain",
      "jaundice",
      "fever",
      "rigors",
      "gallstoneContext",
      "hypotension",
      "confusion",
    ],
    requiredAnyFeatures: ["fever", "rigors"],
  },
  {
    diagnosis: "Acute cholecystitis",
    threshold: 4,
    points: 5,
    reason: "acute cholecystitis pattern",
    features: [
      "ruqPain",
      "persistentRuqPain",
      "localizedRuqTenderness",
      "murphysSign",
      "fever",
      "nausea",
      "vomiting",
      "postPrandialPain",
      "gallstoneContext",
    ],
    requiredAnyFeatures: ["murphysSign", "persistentRuqPain", "localizedRuqTenderness"],
  },
  {
    diagnosis: "Choledocholithiasis / obstructive jaundice",
    threshold: 4,
    points: 5,
    reason: "obstructive jaundice pattern",
    features: [
      "jaundice",
      "darkUrine",
      "paleStools",
      "pruritus",
      "obstructiveJaundiceLanguage",
      "gallstoneContext",
      "ruqPain",
    ],
    requiredAnyFeatures: ["jaundice", "darkUrine", "paleStools", "obstructiveJaundiceLanguage"],
  },
  {
    diagnosis: "Biliary colic / gallstone disease",
    threshold: 4,
    points: 5,
    reason: "biliary colic pattern",
    features: [
      "ruqPain",
      "postPrandialPain",
      "recurrentBiliaryPain",
      "wellBetweenEpisodes",
      "gallstoneContext",
      "nausea",
    ],
    requiredAnyFeatures: ["postPrandialPain", "recurrentBiliaryPain", "wellBetweenEpisodes"],
  },
  {
    diagnosis: "Acute coronary syndrome",
    threshold: 3,
    points: 4,
    reason: "ACS pattern",
    features: [
      "chestPain",
      "jawPain",
      "armPain",
      "sweating",
      "nausea",
      "indigestionLikeChestPain",
      "abdominalPain",
      "hypertension",
      "smoker",
      "sob",
      "collapse",
    ],
    requiredAnyFeatures: ["chestPain", "jawPain", "armPain", "indigestionLikeChestPain"],
  },
  {
    diagnosis: "Pulmonary embolism",
    threshold: 5,
    points: 5,
    reason: "PE pattern",
    features: [
      "chestPain",
      "sob",
      "suddenOnset",
      "tachycardia",
      "tachypnoea",
      "pleuriticPain",
      "hypoxia",
      "collapse",
      "recentSurgery",
      "immobility",
      "longHaulTravel",
    ],
  },
  {
    diagnosis: "Pneumothorax",
    threshold: 3,
    points: 9,
    reason: "pneumothorax pattern",
    features: [
      "sob",
      "pleuriticPain",
      "unilateralReducedAirEntry",
      "trauma",
      "suddenOnset",
      "tallThinHabitus",
      "recentChestDrain",
      "previousPneumothorax",
      "smoker",
    ],
    requiredAnyFeatures: ["unilateralReducedAirEntry", "pleuriticPain", "trauma"],
  },
  {
    diagnosis: "Meningitis / encephalitis",
    threshold: 3,
    points: 5,
    reason: "meningitis / encephalitis pattern",
    features: [
      "confusion",
      "fever",
      "headache",
      "neckStiffness",
      "vomiting",
      "photophobia",
      "sharedAccommodation",
      "recentInfection",
    ],
    requiredAnyFeatures: ["headache", "neckStiffness", "photophobia", "confusion"],
  },
  {
    diagnosis: "GI bleed",
    threshold: 2,
    points: 5,
    reason: "GI bleed instability pattern",
    features: ["giBleed", "prBleeding", "melaena", "haematemesis"],
  },
  {
    diagnosis: "Sepsis",
    threshold: 4,
    points: 5,
    reason: "sepsis pattern",
    features: ["fever", "hypothermia", "rigors", "infectionSource", "hypotension", "tachycardia", "tachypnoea", "confusion", "sob", "collapse"],
    requiredAnyFeatures: ["fever", "hypothermia", "rigors", "infectionSource"],
  },
  {
    diagnosis: "Musculoskeletal chest pain",
    threshold: 3,
    points: 5,
    reason: "musculoskeletal chest wall pattern",
    features: [
      "chestPain",
      "reproducibleChestWallTenderness",
      "movementRelatedChestPain",
      "postLiftingOnset",
    ],
    requiredAnyFeatures: ["reproducibleChestWallTenderness", "movementRelatedChestPain"],
  },
  {
    diagnosis: "Migraine",
    threshold: 4,
    points: 4,
    reason: "migraine pattern",
    features: [
      "headache",
      "photophobia",
      "nausea",
      "visualAura",
      "throbbingHeadache",
      "unilateralHeadache",
      "recurrentHeadache",
      "wellIntervals",
    ],
    requiredAnyFeatures: ["photophobia", "visualAura", "throbbingHeadache", "unilateralHeadache"],
  },
  {
    diagnosis: "Tension headache",
    threshold: 3,
    points: 4,
    reason: "tension headache pattern",
    features: [
      "headache",
      "gradualOnset",
      "bilateralHeadache",
      "bandLikeHeadache",
      "stressTrigger",
      "poorSleep",
    ],
    requiredAnyFeatures: ["bilateralHeadache", "bandLikeHeadache", "stressTrigger"],
  },
  {
    diagnosis: "Temporal arteritis",
    threshold: 3,
    points: 5,
    reason: "temporal arteritis pattern",
    features: [
      "headache",
      "temporalHeadache",
      "scalpTenderness",
      "jawClaudication",
      "transientVisualSymptoms",
      "pmrLikeSymptoms",
    ],
    requiredAnyFeatures: ["jawClaudication", "scalpTenderness", "transientVisualSymptoms"],
  },
  {
    diagnosis: "Asthma exacerbation",
    threshold: 4,
    points: 6,
    reason: "asthma exacerbation pattern",
    features: [
      "sob",
      "wheeze",
      "knownAsthma",
      "recentInfection",
      "increasedInhalerUse",
      "difficultySpeaking",
      "tachypnoea",
      "hypoxia",
    ],
    requiredAnyFeatures: ["wheeze", "knownAsthma", "increasedInhalerUse", "difficultySpeaking"],
  },
  {
    diagnosis: "Heart failure",
    threshold: 3,
    points: 5,
    reason: "heart failure pattern",
    features: ["sob", "orthopnoea", "ankleSwelling", "hypoxia", "tachypnoea"],
    requiredAnyFeatures: ["orthopnoea", "ankleSwelling"],
  },
  {
    diagnosis: "Panic / anxiety",
    threshold: 2,
    points: 4,
    reason: "panic / anxiety pattern",
    features: ["panicFeatures", "sob", "chestPain", "tachypnoea"],
    requiredAnyFeatures: ["panicFeatures"],
  },
  {
    diagnosis: "COPD exacerbation",
    threshold: 4,
    points: 5,
    reason: "COPD exacerbation pattern",
    features: [
      "sob",
      "wheeze",
      "knownCopd",
      "sputumChange",
      "productiveCough",
      "progressiveCourse",
      "hypoxia",
      "tachypnoea",
    ],
    requiredAnyFeatures: ["knownCopd", "sputumChange", "progressiveCourse"],
  },
];

function has(features: ExtractedFeatures, key: string) {
  return features.matchedFeatures.includes(key);
}

export function getDiagnosisBoosts(features: ExtractedFeatures): DiagnosisBoost[] {
  return DIAGNOSIS_BOOST_RULES.flatMap((boostRule) => {
    if (
      boostRule.requiredAnyFeatures &&
      !boostRule.requiredAnyFeatures.some((feature) => has(features, feature))
    ) {
      return [];
    }

    const matchCount = boostRule.features.filter((feature) => has(features, feature)).length;

    if (matchCount < boostRule.threshold) {
      return [];
    }

    return [
      {
        diagnosis: boostRule.diagnosis,
        reason: boostRule.reason,
        points: boostRule.points,
      },
    ];
  });
}
