const FEATURE_LABELS: Record<string, string> = {
  chestPain: "chest pain",
  suddenOnset: "sudden onset",
  tearingPain: "tearing quality",
  backRadiation: "back radiation",
  collapse: "collapse / syncope",
  pulsatileAbdomen: "pulsatile abdomen",
  smoker: "smoking history",
  smokingHistory: "smoking history",
  hypertension: "hypertension",
  jawPain: "jaw pain",
  armPain: "arm pain",
  sweating: "sweating",
  nausea: "nausea",
  indigestionLikeChestPain: "indigestion-like chest pain",
  heartburn: "heartburn / retrosternal burning",
  worseAfterMeals: "worse after meals",
  worseLyingFlat: "worse lying flat",
  acidRegurgitation: "acid regurgitation",
  antacidRelief: "antacid relief",
  abdominalPain: "abdominal pain",
  upperAbdominalPain: "upper abdominal pain",
  epigastricPain: "epigastric pain",
  ruqPain: "right upper quadrant pain",
  rifPain: "right iliac fossa / right lower quadrant pain",
  llqPain: "left lower quadrant pain",
  generalizedAbdominalPain: "generalized abdominal pain",
  pelvicPain: "pelvic pain",
  suprapubicPain: "suprapubic pain",
  flankPain: "flank pain",
  loinToGroinPain: "loin-to-groin pain",
  testicularPain: "testicular pain",
  constantPain: "constant pain",
  episodicPain: "episodic pain",
  recurrentAttacks: "recurrent attacks",
  painSettlesBetweenEpisodes: "pain settles between episodes",
  progressivePain: "progressive pain",
  painMigrationToRIF: "migration of pain to right iliac fossa",
  severePain: "severe pain",
  colickyPain: "colicky pain",
  painRadiatesToBack: "pain radiating to the back",
  painWorseOnMovement: "pain worse on movement",
  painWorseWithCough: "pain worse with cough",
  lyingStill: "lying still due to pain",
  restless: "restless / cannot get comfortable",
  localizedTenderness: "localized tenderness",
  ruqTenderness: "RUQ tenderness",
  rifTenderness: "RIF tenderness",
  distension: "abdominal distension",
  herniaPresent: "hernia present",
  incarceratedHernia: "incarcerated hernia",
  bowelHabitChange: "bowel habit change",
  obstipation: "obstipation",
  unableToPassFlatus: "unable to pass flatus",
  anorexia: "anorexia",
  jaundice: "jaundice",
  darkUrine: "dark urine",
  paleStools: "pale stools",
  pruritus: "pruritus / itching",
  murphysSign: "Murphy's sign",
  localizedRuqTenderness: "localized RUQ tenderness",
  persistentRuqPain: "persistent RUQ pain",
  postPrandialPain: "post-prandial / fatty-meal pain",
  recurrentBiliaryPain: "recurrent biliary-type pain",
  wellBetweenEpisodes: "well between episodes",
  obstructiveJaundiceLanguage: "obstructive jaundice language",
  diarrhoea: "diarrhoea",
  constipation: "constipation",
  prBleeding: "PR bleeding",
  melaena: "melaena",
  haematemesis: "haematemesis",
  haemoptysis: "haemoptysis",
  burningPain: "burning pain",
  rigors: "rigors",
  infectionSource: "infection source",
  alcoholExcess: "alcohol excess",
  heavyAlcoholIntake: "heavy alcohol intake",
  gallstoneContext: "gallstone context",
  gallstoneHistory: "gallstone history",
  bingeDrinking: "binge drinking",
  pepticUlcerDisease: "peptic ulcer disease",
  pepticUlcerHistory: "peptic ulcer history",
  nsaidUse: "NSAID use",
  severeConstantUpperAbdominalPain: "severe constant upper abdominal pain",
  guardingRigidity: "guarding / rigidity",
  abdominalMovementPain: "pain worse on movement or coughing",
  perforationLanguage: "perforation / free air language",
  recentSurgery: "recent surgery",
  immobility: "immobility",
  longHaulTravel: "long-haul travel",
  unilateralReducedAirEntry: "unilateral reduced air entry",
  tallThinHabitus: "tall thin habitus",
  recentChestDrain: "recent chest drain",
  previousPneumothorax: "previous pneumothorax",
  trauma: "trauma pattern",
  productiveCough: "productive cough",
  progressiveCourse: "progressive course",
  wheeze: "wheeze",
  knownAsthma: "known asthma",
  knownCopd: "known COPD",
  increasedInhalerUse: "increased inhaler use",
  difficultySpeaking: "difficulty speaking full sentences",
  sputumChange: "sputum change",
  reproducibleChestWallTenderness: "reproducible chest wall tenderness",
  movementRelatedChestPain: "movement-related chest pain",
  postLiftingOnset: "post-lifting onset",
  painOutOfProportion: "pain out of proportion",
  painSevereButExamMild: "severe pain with mild abdominal findings",
  migrationToRIF: "migration to right iliac fossa",
  vaginalBleeding: "vaginal bleeding",
  pregnancyPossible: "pregnancy possible",
  missedPeriod: "missed period",
  postpartum: "postpartum context",
  recentMiscarriage: "recent miscarriage",
  unilateralTesticularPain: "unilateral testicular pain",
  backPain: "back pain",
  urinaryRetention: "urinary retention",
  dysuria: "dysuria",
  frequency: "urinary frequency",
  haematuria: "haematuria",
  cvaTenderness: "costovertebral angle tenderness",
  dizziness: "dizziness / presyncope",
  pallor: "pallor",
  saddleNumbness: "saddle numbness",
  bilateralLegSymptoms: "bilateral leg symptoms",
  transientFocalDeficit: "transient focal deficit",
  gradualSpreadPositiveSymptoms: "gradual spread of positive neuro symptoms",
  urinarySymptoms: "urinary symptoms",
  orthopnoea: "orthopnoea",
  ankleSwelling: "ankle swelling / oedema",
  diabeticContext: "diabetic context",
  polyuria: "polyuria",
  polydipsia: "polydipsia",
  ketosisBreath: "ketosis / ketotic breath",
  hypoglycaemiaCue: "hypoglycaemia cues",
  panicFeatures: "panic / anxiety features",
  positivePregnancyTest: "positive pregnancy test",
  adnexalPain: "adnexal pain",
  acsEquivalentPain: "ACS-equivalent epigastric / upper abdominal pain",
  shock: "shock",
  dehydration: "dehydration",
  af: "atrial fibrillation",
  atrialFibrillation: "atrial fibrillation",
  thunderclap: "thunderclap onset",
  headache: "headache",
  visualAura: "visual aura",
  throbbingHeadache: "throbbing headache",
  unilateralHeadache: "unilateral headache",
  recurrentHeadache: "recurrent stereotyped headaches",
  wellIntervals: "well intervals between episodes",
  gradualOnset: "gradual onset",
  bilateralHeadache: "bilateral headache",
  bandLikeHeadache: "band-like headache",
  stressTrigger: "stress trigger",
  poorSleep: "poor sleep",
  vomiting: "vomiting",
  neckStiffness: "neck stiffness",
  photophobia: "photophobia",
  sharedAccommodation: "shared accommodation",
  recentInfection: "recent infection",
  ibdContext: "IBD / ulcerative colitis context",
  fatigue: "fatigue",
  dryEyesMouth: "dry eyes / dry mouth",
  chronicCourse: "chronic course",
  confusion: "confusion",
  fluctuation: "fluctuating course",
  focalNeurology: "focal neurology",
  sob: "shortness of breath",
  hypoxia: "hypoxia",
  pleuriticPain: "pleuritic pain",
  fever: "fever",
  hypothermia: "hypothermia",
  hypotension: "hypotension / shock",
  tachycardia: "tachycardia",
  tachypnoea: "tachypnoea",
  giBleed: "GI bleed evidence",
  olderAge: "older age",
  vascularDisease: "vascular disease",
  previousAbdominalSurgery: "previous abdominal surgery",
  knownHernia: "known hernia",
  femaleOfChildbearingAge: "female of childbearing age",
  scalpTenderness: "scalp tenderness",
  jawClaudication: "jaw claudication",
  temporalHeadache: "temporal headache",
  transientVisualSymptoms: "transient visual symptoms",
  pmrLikeSymptoms: "PMR-like symptoms",
};

export function formatFeatureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}
