const FEATURE_LABELS: Record<string, string> = {
  chest_pain: "chest pain",
  sudden_onset: "sudden onset",
  tearing_pain: "tearing quality",
  back_radiation: "back radiation",
  collapse: "collapse / syncope",
  pulsatile_abdomen: "pulsatile abdomen",
  smoker: "smoking history",
  smoking_history: "smoking history",
  hypertension: "hypertension",
  jaw_pain: "jaw pain",
  arm_pain: "arm pain",
  sweating: "sweating",
  nausea: "nausea",
  indigestion_like_chest_pain: "indigestion-like chest pain",
  heartburn: "heartburn / retrosternal burning",
  worse_after_meals: "worse after meals",
  worse_lying_flat: "worse lying flat",
  acid_regurgitation: "acid regurgitation",
  antacid_relief: "antacid relief",
  abdominal_pain: "abdominal pain",
  upper_abdominal_pain: "upper abdominal pain",
  epigastric_pain: "epigastric pain",
  ruq_pain: "right upper quadrant pain",
  rif_pain: "right iliac fossa / right lower quadrant pain",
  llq_pain: "left lower quadrant pain",
  generalized_abdominal_pain: "generalized abdominal pain",
  pelvic_pain: "pelvic pain",
  suprapubic_pain: "suprapubic pain",
  flank_pain: "flank pain",
  loin_to_groin_pain: "loin-to-groin pain",
  testicular_pain: "testicular pain",
  constant_pain: "constant pain",
  episodic_pain: "episodic pain",
  recurrent_attacks: "recurrent attacks",
  pain_settles_between_episodes: "pain settles between episodes",
  progressive_pain: "progressive pain",
  pain_migration_to_rif: "migration of pain to right iliac fossa",
  severe_pain: "severe pain",
  colicky_pain: "colicky pain",
  pain_radiates_to_back: "pain radiating to the back",
  pain_worse_on_movement: "pain worse on movement",
  pain_worse_with_cough: "pain worse with cough",
  lying_still: "lying still due to pain",
  restless: "restless / cannot get comfortable",
  localized_tenderness: "localized tenderness",
  ruq_tenderness: "RUQ tenderness",
  rif_tenderness: "RIF tenderness",
  distension: "abdominal distension",
  hernia_present: "hernia present",
  incarcerated_hernia: "incarcerated hernia",
  bowel_habit_change: "bowel habit change",
  obstipation: "obstipation",
  unable_to_pass_flatus: "unable to pass flatus",
  anorexia: "anorexia",
  jaundice: "jaundice",
  dark_urine: "dark urine",
  pale_stools: "pale stools",
  pruritus: "pruritus / itching",
  murphys_sign: "Murphy's sign",
  localized_ruq_tenderness: "localized RUQ tenderness",
  persistent_ruq_pain: "persistent RUQ pain",
  post_prandial_pain: "post-prandial / fatty-meal pain",
  recurrent_biliary_pain: "recurrent biliary-type pain",
  well_between_episodes: "well between episodes",
  obstructive_jaundice_language: "obstructive jaundice language",
  diarrhoea: "diarrhoea",
  constipation: "constipation",
  pr_bleeding: "PR bleeding",
  melaena: "melaena",
  haematemesis: "haematemesis",
  haemoptysis: "haemoptysis",
  burning_pain: "burning pain",
  rigors: "rigors",
  infection_source: "infection source",
  alcohol_excess: "alcohol excess",
  heavy_alcohol_intake: "heavy alcohol intake",
  gallstone_context: "gallstone context",
  gallstone_history: "gallstone history",
  binge_drinking: "binge drinking",
  peptic_ulcer_disease: "peptic ulcer disease",
  peptic_ulcer_history: "peptic ulcer history",
  nsaid_use: "NSAID use",
  severe_constant_upper_abdominal_pain: "severe constant upper abdominal pain",
  guarding_rigidity: "guarding / rigidity",
  abdominal_movement_pain: "pain worse on movement or coughing",
  perforation_language: "perforation / free air language",
  recent_surgery: "recent surgery",
  immobility: "immobility",
  long_haul_travel: "long-haul travel",
  unilateral_reduced_air_entry: "unilateral reduced air entry",
  tall_thin_habitus: "tall thin habitus",
  recent_chest_drain: "recent chest drain",
  previous_pneumothorax: "previous pneumothorax",
  trauma: "trauma pattern",
  productive_cough: "productive cough",
  progressive_course: "progressive course",
  wheeze: "wheeze",
  known_asthma: "known asthma",
  known_copd: "known COPD",
  increased_inhaler_use: "increased inhaler use",
  difficulty_speaking: "difficulty speaking full sentences",
  sputum_change: "sputum change",
  reproducible_chest_wall_tenderness: "reproducible chest wall tenderness",
  movement_related_chest_pain: "movement-related chest pain",
  post_lifting_onset: "post-lifting onset",
  pain_out_of_proportion: "pain out of proportion",
  pain_severe_but_exam_mild: "severe pain with mild abdominal findings",
  migration_to_rif: "migration to right iliac fossa",
  vaginal_bleeding: "vaginal bleeding",
  pregnancy_possible: "pregnancy possible",
  missed_period: "missed period",
  postpartum: "postpartum context",
  recent_miscarriage: "recent miscarriage",
  unilateral_testicular_pain: "unilateral testicular pain",
  back_pain: "back pain",
  urinary_retention: "urinary retention",
  dysuria: "dysuria",
  frequency: "urinary frequency",
  haematuria: "haematuria",
  cva_tenderness: "costovertebral angle tenderness",
  dizziness: "dizziness / presyncope",
  pallor: "pallor",
  saddle_numbness: "saddle numbness",
  bilateral_leg_symptoms: "bilateral leg symptoms",
  transient_focal_deficit: "transient focal deficit",
  gradual_spread_positive_symptoms: "gradual spread of positive neuro symptoms",
  urinary_symptoms: "urinary symptoms",
  orthopnoea: "orthopnoea",
  ankle_swelling: "ankle swelling / oedema",
  diabetic_context: "diabetic context",
  polyuria: "polyuria",
  polydipsia: "polydipsia",
  ketosis_breath: "ketosis / ketotic breath",
  hypoglycaemia_cue: "hypoglycaemia cues",
  panic_features: "panic / anxiety features",
  positive_pregnancy_test: "positive pregnancy test",
  adnexal_pain: "adnexal pain",
  acs_equivalent_pain: "ACS-equivalent epigastric / upper abdominal pain",
  shock: "shock",
  dehydration: "dehydration",
  af: "atrial fibrillation",
  atrial_fibrillation: "atrial fibrillation",
  thunderclap: "thunderclap onset",
  headache: "headache",
  visual_aura: "visual aura",
  throbbing_headache: "throbbing headache",
  unilateral_headache: "unilateral headache",
  recurrent_headache: "recurrent stereotyped headaches",
  well_intervals: "well intervals between episodes",
  gradual_onset: "gradual onset",
  bilateral_headache: "bilateral headache",
  band_like_headache: "band-like headache",
  stress_trigger: "stress trigger",
  poor_sleep: "poor sleep",
  vomiting: "vomiting",
  neck_stiffness: "neck stiffness",
  photophobia: "photophobia",
  shared_accommodation: "shared accommodation",
  recent_infection: "recent infection",
  ibd_context: "IBD / ulcerative colitis context",
  fatigue: "fatigue",
  dry_eyes_mouth: "dry eyes / dry mouth",
  chronic_course: "chronic course",
  confusion: "confusion",
  fluctuation: "fluctuating course",
  focal_neurology: "focal neurology",
  sob: "shortness of breath",
  hypoxia: "hypoxia",
  pleuritic_pain: "pleuritic pain",
  fever: "fever",
  hypothermia: "hypothermia",
  hypotension: "hypotension / shock",
  tachycardia: "tachycardia",
  tachypnoea: "tachypnoea",
  gi_bleed: "GI bleed evidence",
  older_age: "older age",
  vascular_disease: "vascular disease",
  previous_abdominal_surgery: "previous abdominal surgery",
  known_hernia: "known hernia",
  female_of_childbearing_age: "female of childbearing age",
  scalp_tenderness: "scalp tenderness",
  jaw_claudication: "jaw claudication",
  temporal_headache: "temporal headache",
  transient_visual_symptoms: "transient visual symptoms",
  pmr_like_symptoms: "PMR-like symptoms",
};

export function formatFeatureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}
