export type GuidelineRule = {
  id: string;
  title: string;
  sourceBody: "NICE" | "GMC" | "HSCNI";
  sourceId: string;
  sourceCoverage: "full" | "partial" | "gap";
  rationale: string;
  triggers: string[];
  boostDiagnoses: string[];
  requiredAnyFeatures?: string[];
};

export const GUIDELINE_RULES: GuidelineRule[] = [
  {
    id: "nice-ng156-aaa-001",
    title: "Ruptured AAA suspicion pattern",
    sourceBody: "NICE",
    sourceId: "NG156",
    sourceCoverage: "full",
    rationale:
      "New abdominal or back pain with collapse or loss of consciousness, especially in an older person with smoking history or hypertension, should push ruptured or symptomatic AAA higher.",
    triggers: [
      "abdominal_pain",
      "back_radiation",
      "back_pain",
      "flank_pain",
      "sudden_onset",
      "collapse",
      "pulsatile_abdomen",
      "smoker",
      "smoking_history",
      "older_age",
      "vascular_disease",
      "hypertension",
      "hypotension",
    ],
    boostDiagnoses: ["Abdominal aortic aneurysm"],
    requiredAnyFeatures: ["collapse", "hypotension", "pulsatile_abdomen"],
  },
  {
    id: "nice-cg95-acs-001",
    title: "ACS suspicion pattern",
    sourceBody: "NICE",
    sourceId: "CG95",
    sourceCoverage: "full",
    rationale:
      "Chest pain or a chest-pain-equivalent pattern such as indigestion-like epigastric discomfort, especially with autonomic features or radiation, should keep acute coronary syndrome high on the differential.",
    triggers: [
      "chest_pain",
      "jaw_pain",
      "arm_pain",
      "indigestion_like_chest_pain",
      "nausea",
      "collapse",
      "sob",
      "hypotension",
      "hypertension",
      "sweating",
    ],
    boostDiagnoses: ["Acute coronary syndrome"],
    requiredAnyFeatures: ["chest_pain", "jaw_pain", "arm_pain", "indigestion_like_chest_pain", "acs_equivalent_pain"],
  },
  {
    id: "nice-ng158-pe-001",
    title: "PE suspicion pattern",
    sourceBody: "NICE",
    sourceId: "NG158",
    sourceCoverage: "full",
    rationale:
      "Breathlessness or pleuritic pain with a meaningful PE signal should prompt formal PE assessment rather than casual exclusion.",
    triggers: [
      "sob",
      "pleuritic_pain",
      "tachycardia",
      "hypoxia",
      "haemoptysis",
      "unilateral_leg_swelling",
      "calf_swelling",
      "dvt_signs",
      "dvt_history",
      "recent_surgery",
      "immobility",
      "long_haul_travel",
      "oestrogen_use",
      "pregnancy_possible",
    ],
    boostDiagnoses: ["Pulmonary embolism"],
    requiredAnyFeatures: ["sob", "pleuritic_pain"],
  },
  {
    id: "wardbrain-gap-severe-asthma-001",
    title: "Severe asthma pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Asthma or wheeze with severe respiratory physiology should escalate asthma exacerbation above reassuring or anxiety explanations.",
    triggers: [
      "known_asthma",
      "asthma_history",
      "wheeze",
      "unable_to_speak_full_sentences",
      "difficulty_speaking",
      "hypoxia",
      "silent_chest",
      "poor_peak_flow",
      "tachypnoea",
      "severe_respiratory_distress",
    ],
    boostDiagnoses: ["Asthma exacerbation"],
    requiredAnyFeatures: ["unable_to_speak_full_sentences", "difficulty_speaking", "hypoxia", "silent_chest", "poor_peak_flow", "tachypnoea"],
  },
  {
    id: "wardbrain-gap-heart-failure-001",
    title: "Acute heart failure / pulmonary oedema pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Dyspnoea with orthopnoea, basal crackles, raised JVP, peripheral oedema, or frothy sputum should promote acute heart failure or pulmonary oedema.",
    triggers: [
      "sob",
      "orthopnoea",
      "paroxysmal_nocturnal_dyspnoea",
      "bibasal_crackles",
      "raised_jvp",
      "peripheral_oedema",
      "ankle_swelling",
      "frothy_sputum",
    ],
    boostDiagnoses: ["Heart failure"],
    requiredAnyFeatures: ["orthopnoea", "paroxysmal_nocturnal_dyspnoea", "bibasal_crackles", "raised_jvp", "peripheral_oedema", "frothy_sputum"],
  },
  {
    id: "wardbrain-gap-tension-pneumothorax-001",
    title: "Tension pneumothorax pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Sudden breathlessness or pleuritic pain with unilateral reduced air entry and instability should escalate possible tension pneumothorax.",
    triggers: [
      "sudden_onset",
      "sob",
      "pleuritic_pain",
      "unilateral_reduced_air_entry",
      "hypoxia",
      "hypotension",
      "tachycardia",
      "severe_respiratory_distress",
    ],
    boostDiagnoses: ["Pneumothorax"],
    requiredAnyFeatures: ["unilateral_reduced_air_entry"],
  },
  {
    id: "wardbrain-gap-dka-breathlessness-001",
    title: "DKA / metabolic acidosis pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Diabetic or hyperglycaemic context with Kussmaul breathing and osmotic or dehydration features should promote DKA as a metabolic cause of breathlessness.",
    triggers: [
      "diabetic_context",
      "hyperglycaemia",
      "kussmaul_breathing",
      "polyuria",
      "polydipsia",
      "vomiting",
      "abdominal_pain",
      "dehydration",
    ],
    boostDiagnoses: ["Diabetic ketoacidosis"],
    requiredAnyFeatures: ["kussmaul_breathing", "hyperglycaemia"],
  },
  {
    id: "nice-cg103-delirium-001",
    title: "Think delirium pattern",
    sourceBody: "NICE",
    sourceId: "CG103",
    sourceCoverage: "full",
    rationale:
      "An acute change in mental state or behaviour over hours to days should trigger active consideration of delirium and a search for the precipitant.",
    triggers: ["confusion", "fever"],
    boostDiagnoses: ["Delirium secondary to infection"],
    requiredAnyFeatures: ["confusion"],
  },
  {
    id: "nice-cg150-headache-001",
    title: "Headache urgent evaluation pattern",
    sourceBody: "NICE",
    sourceId: "CG150",
    sourceCoverage: "full",
    rationale:
      "Sudden severe headache, especially with vomiting, neurological features, or reduced consciousness, should not be reassured as a simple primary headache.",
    triggers: ["thunderclap", "headache", "vomiting", "focal_neurology", "collapse"],
    boostDiagnoses: ["Subarachnoid haemorrhage", "Stroke / neurological emergency"],
    requiredAnyFeatures: ["thunderclap", "headache", "focal_neurology"],
  },
  {
    id: "nice-cg150-thunderclap-headache-001",
    title: "Thunderclap headache pattern",
    sourceBody: "NICE",
    sourceId: "CG150",
    sourceCoverage: "full",
    rationale:
      "A sudden thunderclap or worst-ever headache is a time-critical secondary-headache pattern and should keep SAH high.",
    triggers: [
      "headache",
      "thunderclap",
      "worst_headache_of_life",
      "sudden_onset",
      "severe_headache",
      "vomiting",
      "collapse",
      "seizure",
    ],
    boostDiagnoses: ["Subarachnoid haemorrhage"],
    requiredAnyFeatures: ["thunderclap", "worst_headache_of_life"],
  },
  {
    id: "nice-cg150-sah-001",
    title: "Suspected SAH pattern",
    sourceBody: "NICE",
    sourceId: "CG150",
    sourceCoverage: "full",
    rationale:
      "Thunderclap headache with vomiting, meningism, collapse, seizure, reduced consciousness, or focal neurology should be treated as suspected SAH until excluded.",
    triggers: [
      "headache",
      "thunderclap",
      "worst_headache_of_life",
      "vomiting",
      "neck_stiffness",
      "collapse",
      "seizure",
      "reduced_consciousness",
      "focal_neurology",
    ],
    boostDiagnoses: ["Subarachnoid haemorrhage"],
    requiredAnyFeatures: ["thunderclap", "worst_headache_of_life"],
  },
  {
    id: "wardbrain-gap-mesenteric-001",
    title: "Mesenteric ischaemia escalation pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Pain out of proportion or severe pain with a mild abdominal examination, especially with atrial fibrillation, vascular disease, or older age, should escalate mesenteric ischaemia sharply above benign abdominal fallbacks.",
    triggers: [
      "abdominal_pain",
      "pain_out_of_proportion",
      "pain_severe_but_exam_mild",
      "af",
      "vascular_disease",
      "older_age",
      "collapse",
      "hypotension",
    ],
    boostDiagnoses: ["Mesenteric ischaemia"],
    requiredAnyFeatures: ["pain_out_of_proportion", "pain_severe_but_exam_mild"],
  },
  {
    id: "wardbrain-gap-perforation-001",
    title: "Perforated viscus / peritonitis pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Sudden abdominal pain with rigidity, generalized peritonism, lying still, or movement/cough pain should escalate perforated viscus or peritonitis above softer upper abdominal diagnoses. Guarding alone is not enough.",
    triggers: [
      "abdominal_pain",
      "sudden_onset",
      "guarding_rigidity",
      "rigidity",
      "peritonism",
      "abdominal_movement_pain",
      "pain_worse_on_movement",
      "pain_worse_with_cough",
      "lying_still",
      "hypotension",
    ],
    boostDiagnoses: ["Perforated viscus"],
    requiredAnyFeatures: [
      "guarding_rigidity",
      "rigidity",
      "peritonism",
      "lying_still",
      "abdominal_movement_pain",
      "pain_worse_on_movement",
      "pain_worse_with_cough",
    ],
  },
  {
    id: "wardbrain-gap-tia-001",
    title: "Transient focal neurological pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "A sudden transient focal deficit should not be dismissed as benign just because symptoms have improved or resolved.",
    triggers: ["focal_neurology", "transient_focal_deficit", "sudden_onset"],
    boostDiagnoses: ["TIA", "Stroke / neurological emergency"],
    requiredAnyFeatures: ["transient_focal_deficit", "focal_neurology"],
  },
  {
    id: "wardbrain-gap-cauda-001",
    title: "Cauda equina pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Urinary retention, saddle sensory change, or bilateral leg symptoms with back pain should escalate cauda equina syndrome urgently.",
    triggers: ["back_pain", "urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
    boostDiagnoses: ["Cauda equina syndrome"],
    requiredAnyFeatures: ["urinary_retention", "saddle_numbness", "bilateral_leg_symptoms"],
  },
  {
    id: "wardbrain-gap-ectopic-001",
    title: "Ectopic pregnancy pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Pregnancy possibility with abdominal or pelvic pain and vaginal bleeding should strongly escalate ectopic pregnancy, especially if there is collapse or shock.",
    triggers: ["pregnancy_possible", "missed_period", "vaginal_bleeding", "abdominal_pain", "pelvic_pain", "collapse", "hypotension"],
    boostDiagnoses: ["Ectopic pregnancy"],
    requiredAnyFeatures: ["vaginal_bleeding", "pregnancy_possible", "missed_period"],
  },
  {
    id: "wardbrain-gap-torsion-001",
    title: "Testicular torsion pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Sudden unilateral testicular pain with vomiting should escalate testicular torsion rather than being absorbed into generic abdominal pain.",
    triggers: ["unilateral_testicular_pain", "sudden_onset", "vomiting"],
    boostDiagnoses: ["Testicular torsion"],
    requiredAnyFeatures: ["unilateral_testicular_pain"],
  },
  {
    id: "wardbrain-gap-hypoglycaemia-001",
    title: "Hypoglycaemia urgent reversible-cause pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Diabetic context with sweating, shakiness, collapse, or confusion should keep hypoglycaemia high as an urgent reversible cause.",
    triggers: ["diabetic_context", "hypoglycaemia_cue", "sweating", "confusion", "collapse"],
    boostDiagnoses: ["Hypoglycaemia"],
    requiredAnyFeatures: ["hypoglycaemia_cue", "confusion", "collapse"],
  },
  {
    id: "wardbrain-gap-meningitis-001",
    title: "Meningitis / encephalitis suspicion pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "This feature cluster should raise urgent concern for meningitis or encephalitis, but the current WardBrain rule is an internal educational pattern rather than a fully source-complete NICE-derived trigger.",
    triggers: ["fever", "headache", "neck_stiffness", "photophobia", "recent_infection", "shared_accommodation"],
    boostDiagnoses: ["Meningitis / encephalitis"],
    requiredAnyFeatures: ["fever", "headache", "neck_stiffness", "photophobia"],
  },
  {
    id: "nice-ng240-meningitis-headache-001",
    title: "Meningitis / encephalitis red-flag pattern",
    sourceBody: "NICE",
    sourceId: "NG240",
    sourceCoverage: "partial",
    rationale:
      "Headache with fever plus meningism, photophobia, rash, confusion, seizure, or reduced consciousness should escalate CNS infection.",
    triggers: [
      "headache",
      "fever",
      "neck_stiffness",
      "photophobia",
      "rash",
      "confusion",
      "seizure",
      "reduced_consciousness",
    ],
    boostDiagnoses: ["Meningitis / encephalitis"],
    requiredAnyFeatures: ["fever", "neck_stiffness", "photophobia", "rash", "confusion", "reduced_consciousness"],
  },
  {
    id: "nice-cks-gca-001",
    title: "Giant cell arteritis pattern",
    sourceBody: "NICE",
    sourceId: "CKS-GCA",
    sourceCoverage: "partial",
    rationale:
      "New headache in a person over 50 with jaw claudication, scalp/temporal tenderness, PMR symptoms, or visual symptoms should raise GCA.",
    triggers: [
      "headache",
      "age_over_50",
      "older_age",
      "temporal_headache",
      "jaw_claudication",
      "scalp_tenderness",
      "temporal_tenderness",
      "visual_loss",
      "transient_visual_loss",
      "pmr_like_symptoms",
    ],
    boostDiagnoses: ["Temporal arteritis"],
    requiredAnyFeatures: ["jaw_claudication", "scalp_tenderness", "temporal_tenderness", "visual_loss", "transient_visual_loss"],
  },
  {
    id: "nice-ng127-raised-icp-001",
    title: "Raised intracranial pressure pattern",
    sourceBody: "NICE",
    sourceId: "NG127",
    sourceCoverage: "partial",
    rationale:
      "Headache worse on waking, lying flat, or coughing, or headache with papilloedema, progressive visual symptoms, cancer, or immunosuppression should raise concern for raised ICP or intracranial mass.",
    triggers: [
      "headache",
      "worse_on_waking",
      "worse_lying_flat",
      "worse_with_coughing",
      "papilloedema",
      "vomiting",
      "visual_disturbance",
      "cancer",
      "immunosuppression",
    ],
    boostDiagnoses: ["Raised intracranial pressure / intracranial mass", "Cerebral venous sinus thrombosis"],
    requiredAnyFeatures: ["worse_on_waking", "worse_lying_flat", "worse_with_coughing", "papilloedema"],
  },
  {
    id: "nice-ng127-focal-neuro-headache-001",
    title: "New focal neurological deficit pattern",
    sourceBody: "NICE",
    sourceId: "NG127",
    sourceCoverage: "partial",
    rationale:
      "Headache with a new focal neurological deficit should be treated as a neurological emergency rather than primary headache.",
    triggers: [
      "headache",
      "focal_neurology",
      "focal_weakness",
      "sensory_loss",
      "aphasia",
      "ataxia",
      "dysarthria",
      "cranial_nerve_deficit",
      "visual_loss",
    ],
    boostDiagnoses: ["Stroke / neurological emergency", "Cerebral venous sinus thrombosis"],
    requiredAnyFeatures: ["focal_neurology", "focal_weakness", "aphasia", "ataxia", "dysarthria", "cranial_nerve_deficit"],
  },
  {
    id: "nice-ng51-sepsis-001",
    title: "High-risk sepsis pattern",
    sourceBody: "NICE",
    sourceId: "NG51",
    sourceCoverage: "partial",
    rationale:
      "Infection with physiological instability such as hypotension, tachycardia, or tachypnoea should trigger sepsis escalation rather than low-acuity viral framing.",
    triggers: ["fever", "tachycardia", "tachypnoea", "infection_source"],
    boostDiagnoses: ["Sepsis"],
    requiredAnyFeatures: ["fever", "hypothermia", "rigors", "infection_source"],
  },
  {
    id: "nice-ng24-gi-bleed-001",
    title: "GI bleed instability pattern",
    sourceBody: "NICE",
    sourceId: "NG24",
    sourceCoverage: "partial",
    rationale:
      "Haematemesis, melaena, or rectal bleeding with haemodynamic compromise should raise urgent concern for unstable gastrointestinal bleeding.",
    triggers: ["gi_bleed", "pr_bleeding", "melaena", "haematemesis", "collapse"],
    boostDiagnoses: ["GI bleed"],
    requiredAnyFeatures: ["gi_bleed", "pr_bleeding", "melaena", "haematemesis"],
  },
  {
    id: "nice-cg188-cholangitis-001",
    title: "Acute cholangitis pattern",
    sourceBody: "NICE",
    sourceId: "CG188",
    sourceCoverage: "partial",
    rationale:
      "RUQ pain with jaundice and fever or rigors should raise urgent concern for acute cholangitis rather than being treated as uncomplicated biliary pain.",
    triggers: [
      "ruq_pain",
      "jaundice",
      "fever",
      "rigors",
      "dark_urine",
      "pale_stools",
    ],
    boostDiagnoses: ["Acute cholangitis"],
    requiredAnyFeatures: ["jaundice", "rigors"],
  },
  {
    id: "wardbrain-gap-bowel-obstruction-001",
    title: "Bowel obstruction strangulation risk pattern",
    sourceBody: "NICE",
    sourceId: "coverage-gap",
    sourceCoverage: "gap",
    rationale:
      "Bowel obstruction with complete obstructive symptoms plus constant pain, guarding, or abnormal physiology should escalate for possible strangulation or bowel ischaemia.",
    triggers: [
      "abdominal_pain",
      "vomiting",
      "distension",
      "obstipation",
      "unable_to_pass_flatus",
      "previous_abdominal_surgery",
      "constant_pain",
      "guarding",
      "tachycardia",
      "hypotension",
      "fever",
      "sepsis_pattern",
    ],
    boostDiagnoses: ["Bowel obstruction"],
    requiredAnyFeatures: ["constant_pain", "guarding", "tachycardia", "hypotension", "fever", "sepsis_pattern"],
  },
  {
    id: "gmc-ai-001",
    title: "AI is advisory, not decisive",
    sourceBody: "GMC",
    sourceId: "GMC-AI",
    sourceCoverage: "full",
    rationale:
      "This tool should support reasoning and presentation, but must not replace supervision, professional judgement, or escalation to a senior clinician.",
    triggers: [],
    boostDiagnoses: [],
  },
];
