import type { FeatureWeightMap, SignatureGate } from "./types";
import { normaliseDiagnosisName } from "./diagnosisAliases";

export type DiagnosisRule = {
  name: string;
  supportive: string[];
  conflicting: string[];
  expectedImportant?: string[];
  supportiveWeights?: FeatureWeightMap;
  conflictingWeights?: FeatureWeightMap;
  strongSignatureGate?: SignatureGate;
};

export const DIAGNOSIS_RULES: DiagnosisRule[] = [
  {
    name: "Acute aortic syndrome",
    supportive: [
      "chestPain",
      "suddenOnset",
      "tearingPain",
      "backRadiation",
      "collapse",
      "hypertension",
    ],
    conflicting: ["fever"],
    expectedImportant: ["suddenOnset", "tearingPain", "backRadiation"],
  },
  {
    name: "Abdominal aortic aneurysm",
    supportive: [
      "abdominalPain",
      "backRadiation",
      "collapse",
      "pulsatileAbdomen",
      "smoker",
      "hypotension",
      "hypertension",
    ],
    conflicting: [],
    expectedImportant: ["collapse", "pulsatileAbdomen"],
  },
  {
    name: "Acute coronary syndrome",
    supportive: [
      "chestPain",
      "jawPain",
      "armPain",
      "sweating",
      "nausea",
      "indigestionLikeChestPain",
      "abdominalPain",
      "collapse",
      "hypertension",
      "smoker",
      "sob",
    ],
    conflicting: [
      "tearingPain",
      "pulsatileAbdomen",
      "backRadiation",
      "reproducibleChestWallTenderness",
      "movementRelatedChestPain",
      "postLiftingOnset",
    ],
    expectedImportant: ["chestPain", "jawPain", "armPain", "sweating", "indigestionLikeChestPain"],
    supportiveWeights: {
      chestPain: 3,
      jawPain: 4,
      armPain: 4,
      sweating: 3,
      nausea: 2,
      indigestionLikeChestPain: 4,
      abdominalPain: 1,
      collapse: 2,
      hypertension: 1,
      smoker: 1,
      sob: 2,
    },
    conflictingWeights: {
      reproducibleChestWallTenderness: 4,
      movementRelatedChestPain: 3,
      postLiftingOnset: 3,
    },
    strongSignatureGate: {
      features: ["chestPain", "jawPain", "armPain", "sweating", "indigestionLikeChestPain"],
      threshold: 2,
      cappedScore: 6,
    },
  },
  {
    name: "Pulmonary embolism",
    supportive: [
      "chestPain",
      "sob",
      "suddenOnset",
      "tachycardia",
      "tachypnoea",
      "collapse",
      "pleuriticPain",
      "hypoxia",
      "haemoptysis",
      "recentSurgery",
      "immobility",
      "longHaulTravel",
    ],
    conflicting: [
      "pulsatileAbdomen",
      "tearingPain",
      "backRadiation",
      "unilateralReducedAirEntry",
      "tallThinHabitus",
      "previousPneumothorax",
      "recentChestDrain",
      "reproducibleChestWallTenderness",
      "postLiftingOnset",
      "wheeze",
    ],
    expectedImportant: ["sob", "suddenOnset"],
    supportiveWeights: {
      chestPain: 3,
      suddenOnset: 3,
      tachycardia: 3,
      tachypnoea: 3,
      sob: 3,
      pleuriticPain: 3,
      hypoxia: 2,
      haemoptysis: 3,
      collapse: 3,
      recentSurgery: 2,
      immobility: 2,
      longHaulTravel: 2,
    },
    conflictingWeights: {
      unilateralReducedAirEntry: 2,
      tallThinHabitus: 1,
      previousPneumothorax: 1,
      recentChestDrain: 1,
      reproducibleChestWallTenderness: 3,
      postLiftingOnset: 3,
      wheeze: 2,
    },
    strongSignatureGate: {
      features: ["chestPain", "sob", "suddenOnset", "pleuriticPain", "hypoxia"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "GORD",
    supportive: [
      "chestPain",
      "indigestionLikeChestPain",
      "heartburn",
      "acidRegurgitation",
      "worseAfterMeals",
      "worseLyingFlat",
      "antacidRelief",
    ],
    conflicting: [
      "suddenOnset",
      "tearingPain",
      "backRadiation",
      "collapse",
      "pulsatileAbdomen",
      "hypotension",
    ],
    expectedImportant: ["indigestionLikeChestPain", "heartburn", "acidRegurgitation"],
    supportiveWeights: {
      chestPain: 1,
      indigestionLikeChestPain: 2,
      heartburn: 4,
      acidRegurgitation: 3,
      worseAfterMeals: 2,
      worseLyingFlat: 2,
      antacidRelief: 3,
    },
  },
  {
    name: "Mesenteric ischaemia",
    supportive: ["abdominalPain", "painOutOfProportion", "af", "collapse"],
    conflicting: ["chestPain"],
    expectedImportant: ["abdominalPain", "painOutOfProportion"],
    supportiveWeights: {
      painOutOfProportion: 3,
      af: 3,
    },
  },
  {
    name: "Subarachnoid haemorrhage",
    supportive: ["thunderclap", "headache", "vomiting", "neckStiffness", "collapse"],
    conflicting: [],
    expectedImportant: ["thunderclap", "headache"],
    supportiveWeights: {
      thunderclap: 6,
      headache: 2,
      vomiting: 1,
      neckStiffness: 1,
      collapse: 3,
    },
    strongSignatureGate: {
      features: ["thunderclap"],
      threshold: 1,
      cappedScore: 4,
    },
  },
  {
    name: "Stroke / neurological emergency",
    supportive: ["confusion", "focalNeurology", "collapse"],
    conflicting: [],
    expectedImportant: ["focalNeurology", "confusion"],
  },
  {
    name: "Delirium secondary to infection",
    supportive: ["confusion", "fever", "infectionSource", "recentInfection", "fluctuation"],
    conflicting: ["focalNeurology", "thunderclap"],
    expectedImportant: ["confusion", "fluctuation"],
    supportiveWeights: {
      confusion: 4,
      fever: 2,
      infectionSource: 3,
      recentInfection: 2,
      fluctuation: 3,
    },
  },
  {
    name: "Gastroenteritis",
    supportive: ["abdominalPain", "diarrhoea", "vomiting", "fever"],
    conflicting: ["painOutOfProportion", "collapse", "af", "hypotension", "giBleed", "prBleeding"],
    expectedImportant: ["abdominalPain", "diarrhoea"],
    conflictingWeights: {
      painOutOfProportion: 3,
      collapse: 3,
      hypotension: 3,
      giBleed: 4,
      prBleeding: 4,
    },
  },
  {
    name: "Pneumonia",
    supportive: [
      "sob",
      "fever",
      "pleuriticPain",
      "hypoxia",
      "productiveCough",
      "infectionSource",
      "rigors",
      "progressiveCourse",
      "sputumChange",
    ],
    conflicting: ["suddenOnset", "collapse"],
    expectedImportant: ["sob", "fever", "productiveCough"],
    supportiveWeights: {
      productiveCough: 3,
      infectionSource: 2,
      rigors: 2,
      progressiveCourse: 3,
      sputumChange: 2,
      fever: 3,
      sob: 2,
      pleuriticPain: 2,
      hypoxia: 2,
    },
    conflictingWeights: {
      suddenOnset: 3,
      collapse: 3,
    },
  },
  {
    name: "Pneumothorax",
    supportive: [
      "chestPain",
      "sob",
      "pleuriticPain",
      "hypoxia",
      "suddenOnset",
      "unilateralReducedAirEntry",
      "tallThinHabitus",
      "recentChestDrain",
      "previousPneumothorax",
      "trauma",
      "smoker",
    ],
    conflicting: ["fever"],
    expectedImportant: ["suddenOnset", "sob", "pleuriticPain"],
    supportiveWeights: {
      suddenOnset: 3,
      hypoxia: 1,
      chestPain: 1,
      sob: 3,
      pleuriticPain: 4,
      unilateralReducedAirEntry: 8,
      tallThinHabitus: 5,
      recentChestDrain: 3,
      previousPneumothorax: 3,
      trauma: 3,
      smoker: 1,
    },
    strongSignatureGate: {
      features: [
        "pleuriticPain",
        "unilateralReducedAirEntry",
        "trauma",
        "tallThinHabitus",
        "previousPneumothorax",
      ],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Migraine",
    supportive: [
      "headache",
      "vomiting",
      "photophobia",
      "nausea",
      "visualAura",
      "throbbingHeadache",
      "unilateralHeadache",
      "recurrentHeadache",
      "wellIntervals",
    ],
    conflicting: ["thunderclap", "focalNeurology", "neckStiffness", "fever", "collapse"],
    expectedImportant: ["headache", "photophobia", "visualAura"],
    supportiveWeights: {
      headache: 2,
      photophobia: 3,
      nausea: 2,
      visualAura: 4,
      throbbingHeadache: 3,
      unilateralHeadache: 2,
      recurrentHeadache: 2,
      wellIntervals: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focalNeurology: 4,
      neckStiffness: 3,
      fever: 2,
      collapse: 3,
    },
    strongSignatureGate: {
      features: [
        "headache",
        "photophobia",
        "visualAura",
        "throbbingHeadache",
        "unilateralHeadache",
        "recurrentHeadache",
      ],
      threshold: 2,
      cappedScore: 1,
    },
  },
  {
    name: "Tension headache",
    supportive: [
      "headache",
      "gradualOnset",
      "bilateralHeadache",
      "bandLikeHeadache",
      "stressTrigger",
      "poorSleep",
    ],
    conflicting: [
      "thunderclap",
      "focalNeurology",
      "neckStiffness",
      "fever",
      "photophobia",
      "vomiting",
      "visualAura",
    ],
    expectedImportant: ["headache", "bilateralHeadache", "bandLikeHeadache"],
    supportiveWeights: {
      headache: 2,
      gradualOnset: 2,
      bilateralHeadache: 3,
      bandLikeHeadache: 4,
      stressTrigger: 2,
      poorSleep: 2,
    },
    conflictingWeights: {
      thunderclap: 5,
      focalNeurology: 4,
      neckStiffness: 3,
      fever: 2,
      photophobia: 2,
      vomiting: 2,
      visualAura: 3,
    },
    strongSignatureGate: {
      features: ["headache", "bilateralHeadache", "bandLikeHeadache", "gradualOnset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Meningitis / encephalitis",
    supportive: [
      "confusion",
      "fever",
      "headache",
      "neckStiffness",
      "vomiting",
      "photophobia",
      "sharedAccommodation",
      "recentInfection",
    ],
    conflicting: [],
    expectedImportant: ["fever", "headache", "neckStiffness"],
    supportiveWeights: {
      neckStiffness: 3,
      confusion: 3,
      photophobia: 3,
      sharedAccommodation: 1,
      recentInfection: 1,
    },
  },
  {
    name: "GI bleed",
    supportive: [
      "giBleed",
      "prBleeding",
      "melaena",
      "haematemesis",
      "collapse",
      "hypotension",
      "tachycardia",
      "vomiting",
      "abdominalPain",
      "alcoholExcess",
      "bingeDrinking",
      "pepticUlcerDisease",
      "nsaidUse",
    ],
    conflicting: ["diarrhoea"],
    expectedImportant: ["giBleed", "hypotension"],
    supportiveWeights: {
      giBleed: 4,
      prBleeding: 3,
      melaena: 3,
      haematemesis: 3,
      hypotension: 1,
      collapse: 2,
      tachycardia: 1,
      vomiting: 1,
      abdominalPain: 1,
      alcoholExcess: 1,
      bingeDrinking: 1,
      pepticUlcerDisease: 2,
      nsaidUse: 2,
    },
    strongSignatureGate: {
      features: ["giBleed", "prBleeding", "melaena", "haematemesis"],
      threshold: 1,
      cappedScore: 5,
    },
  },
  {
    name: "Sepsis",
    supportive: [
      "fever",
      "hypothermia",
      "rigors",
      "infectionSource",
      "hypotension",
      "tachycardia",
      "tachypnoea",
      "confusion",
      "sob",
      "collapse",
    ],
    conflicting: [],
    expectedImportant: ["fever", "hypotension", "tachycardia"],
    supportiveWeights: {
      fever: 3,
      hypothermia: 3,
      rigors: 3,
      infectionSource: 3,
      hypotension: 1,
      tachycardia: 1,
      tachypnoea: 1,
      confusion: 3,
      sob: 1,
      collapse: 1,
    },
    strongSignatureGate: {
      features: ["fever", "hypothermia", "rigors", "infectionSource"],
      threshold: 1,
      cappedScore: 3,
    },
  },
  {
    name: "Viral illness",
    supportive: ["fever", "headache", "vomiting"],
    conflicting: ["hypotension", "collapse", "confusion"],
    expectedImportant: ["fever"],
    conflictingWeights: {
      hypotension: 4,
      collapse: 3,
      confusion: 3,
    },
  },
  {
    name: "Temporal arteritis",
    supportive: [
      "headache",
      "temporalHeadache",
      "scalpTenderness",
      "jawClaudication",
      "transientVisualSymptoms",
      "pmrLikeSymptoms",
    ],
    conflicting: ["thunderclap", "vomiting", "focalNeurology"],
    expectedImportant: ["temporalHeadache", "jawClaudication", "transientVisualSymptoms"],
    supportiveWeights: {
      temporalHeadache: 3,
      scalpTenderness: 3,
      jawClaudication: 5,
      transientVisualSymptoms: 4,
      pmrLikeSymptoms: 3,
      headache: 1,
    },
    strongSignatureGate: {
      features: ["temporalHeadache", "jawClaudication", "transientVisualSymptoms", "scalpTenderness"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "Musculoskeletal chest pain",
    supportive: [
      "chestPain",
      "reproducibleChestWallTenderness",
      "movementRelatedChestPain",
      "postLiftingOnset",
    ],
    conflicting: [
      "hypoxia",
      "tachycardia",
      "collapse",
      "haemoptysis",
      "jawPain",
      "armPain",
      "sweating",
    ],
    expectedImportant: ["reproducibleChestWallTenderness", "movementRelatedChestPain"],
    supportiveWeights: {
      reproducibleChestWallTenderness: 5,
      movementRelatedChestPain: 4,
      postLiftingOnset: 3,
      chestPain: 1,
    },
    conflictingWeights: {
      hypoxia: 3,
      tachycardia: 2,
      collapse: 3,
      haemoptysis: 4,
      jawPain: 3,
      armPain: 3,
      sweating: 2,
    },
    strongSignatureGate: {
      features: ["reproducibleChestWallTenderness", "movementRelatedChestPain", "postLiftingOnset"],
      threshold: 2,
      cappedScore: 2,
    },
  },
  {
    name: "Asthma exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "knownAsthma",
      "increasedInhalerUse",
      "difficultySpeaking",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["chestPain", "haemoptysis", "fever"],
    expectedImportant: ["sob", "wheeze", "knownAsthma"],
    supportiveWeights: {
      sob: 3,
      wheeze: 4,
      knownAsthma: 3,
      increasedInhalerUse: 3,
      difficultySpeaking: 3,
      hypoxia: 2,
      tachypnoea: 2,
    },
    strongSignatureGate: {
      features: ["sob", "wheeze", "knownAsthma", "increasedInhalerUse"],
      threshold: 2,
      cappedScore: 3,
    },
  },
  {
    name: "COPD exacerbation",
    supportive: [
      "sob",
      "wheeze",
      "knownCopd",
      "sputumChange",
      "productiveCough",
      "progressiveCourse",
      "hypoxia",
      "tachypnoea",
    ],
    conflicting: ["chestPain", "haemoptysis"],
    expectedImportant: ["sob", "knownCopd", "progressiveCourse"],
    supportiveWeights: {
      sob: 3,
      wheeze: 3,
      knownCopd: 4,
      sputumChange: 3,
      productiveCough: 2,
      progressiveCourse: 3,
      hypoxia: 2,
      tachypnoea: 2,
    },
    strongSignatureGate: {
      features: ["sob", "knownCopd", "progressiveCourse", "sputumChange"],
      threshold: 2,
      cappedScore: 3,
    },
  },
];

export function findDiagnosisRule(name: string): DiagnosisRule | undefined {
  const canonicalName = normaliseDiagnosisName(name);

  return DIAGNOSIS_RULES.find(
    (diagnosisRule) => diagnosisRule.name.toLowerCase() === canonicalName.toLowerCase(),
  );
}
