const FEATURE_LABELS: Record<string, string> = {
  chestPain: "chest pain",
  suddenOnset: "sudden onset",
  tearingPain: "tearing quality",
  backRadiation: "back radiation",
  collapse: "collapse / syncope",
  pulsatileAbdomen: "pulsatile abdomen",
  smoker: "smoking history",
  hypertension: "hypertension",
  jawPain: "jaw pain",
  armPain: "arm pain",
  sweating: "sweating",
  nausea: "nausea",
  indigestionLikeChestPain: "indigestion-like chest pain",
  heartburn: "heartburn / retrosternal burning",
  worseAfterMeals: "worse after meals",
  worseLyingFlat: "worse lying flat",
  acidRegurgitation: "acid regurgitation",
  antacidRelief: "antacid relief",
  abdominalPain: "abdominal pain",
  diarrhoea: "diarrhoea",
  constipation: "constipation",
  prBleeding: "PR bleeding",
  melaena: "melaena",
  haematemesis: "haematemesis",
  haemoptysis: "haemoptysis",
  rigors: "rigors",
  infectionSource: "infection source",
  alcoholExcess: "alcohol excess",
  bingeDrinking: "binge drinking",
  pepticUlcerDisease: "peptic ulcer disease",
  nsaidUse: "NSAID use",
  recentSurgery: "recent surgery",
  immobility: "immobility",
  longHaulTravel: "long-haul travel",
  unilateralReducedAirEntry: "unilateral reduced air entry",
  tallThinHabitus: "tall thin habitus",
  recentChestDrain: "recent chest drain",
  previousPneumothorax: "previous pneumothorax",
  trauma: "trauma pattern",
  productiveCough: "productive cough",
  progressiveCourse: "progressive course",
  wheeze: "wheeze",
  knownAsthma: "known asthma",
  knownCopd: "known COPD",
  increasedInhalerUse: "increased inhaler use",
  difficultySpeaking: "difficulty speaking full sentences",
  sputumChange: "sputum change",
  reproducibleChestWallTenderness: "reproducible chest wall tenderness",
  movementRelatedChestPain: "movement-related chest pain",
  postLiftingOnset: "post-lifting onset",
  painOutOfProportion: "pain out of proportion",
  af: "atrial fibrillation",
  thunderclap: "thunderclap onset",
  headache: "headache",
  visualAura: "visual aura",
  throbbingHeadache: "throbbing headache",
  unilateralHeadache: "unilateral headache",
  recurrentHeadache: "recurrent stereotyped headaches",
  wellIntervals: "well intervals between episodes",
  gradualOnset: "gradual onset",
  bilateralHeadache: "bilateral headache",
  bandLikeHeadache: "band-like headache",
  stressTrigger: "stress trigger",
  poorSleep: "poor sleep",
  vomiting: "vomiting",
  neckStiffness: "neck stiffness",
  photophobia: "photophobia",
  sharedAccommodation: "shared accommodation",
  recentInfection: "recent infection",
  confusion: "confusion",
  fluctuation: "fluctuating course",
  focalNeurology: "focal neurology",
  sob: "shortness of breath",
  hypoxia: "hypoxia",
  pleuriticPain: "pleuritic pain",
  fever: "fever",
  hypothermia: "hypothermia",
  hypotension: "hypotension / shock",
  tachycardia: "tachycardia",
  tachypnoea: "tachypnoea",
  giBleed: "GI bleed evidence",
  scalpTenderness: "scalp tenderness",
  jawClaudication: "jaw claudication",
  temporalHeadache: "temporal headache",
  transientVisualSymptoms: "transient visual symptoms",
  pmrLikeSymptoms: "PMR-like symptoms",
};

export function formatFeatureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}
