const FEATURE_LABELS: Record<string, string> = {
  chestPain: "chest pain",
  suddenOnset: "sudden onset",
  tearingPain: "tearing quality",
  backRadiation: "back radiation",
  collapse: "collapse / syncope",
  pulsatileAbdomen: "pulsatile abdomen",
  smoker: "smoking history",
  hypertension: "hypertension",
  jawPain: "jaw pain",
  armPain: "arm pain",
  sweating: "sweating",
  nausea: "nausea",
  indigestionLikeChestPain: "indigestion-like chest pain",
  abdominalPain: "abdominal pain",
  diarrhoea: "diarrhoea",
  constipation: "constipation",
  prBleeding: "PR bleeding",
  melaena: "melaena",
  haematemesis: "haematemesis",
  haemoptysis: "haemoptysis",
  rigors: "rigors",
  infectionSource: "infection source",
  alcoholExcess: "alcohol excess",
  bingeDrinking: "binge drinking",
  pepticUlcerDisease: "peptic ulcer disease",
  nsaidUse: "NSAID use",
  recentSurgery: "recent surgery",
  immobility: "immobility",
  longHaulTravel: "long-haul travel",
  unilateralReducedAirEntry: "unilateral reduced air entry",
  tallThinHabitus: "tall thin habitus",
  recentChestDrain: "recent chest drain",
  previousPneumothorax: "previous pneumothorax",
  trauma: "trauma pattern",
  painOutOfProportion: "pain out of proportion",
  af: "atrial fibrillation",
  thunderclap: "thunderclap onset",
  headache: "headache",
  vomiting: "vomiting",
  neckStiffness: "neck stiffness",
  photophobia: "photophobia",
  sharedAccommodation: "shared accommodation",
  recentInfection: "recent infection",
  confusion: "confusion",
  focalNeurology: "focal neurology",
  sob: "shortness of breath",
  hypoxia: "hypoxia",
  pleuriticPain: "pleuritic pain",
  fever: "fever",
  hypothermia: "hypothermia",
  hypotension: "hypotension / shock",
  tachycardia: "tachycardia",
  tachypnoea: "tachypnoea",
  giBleed: "GI bleed evidence",
};

export function formatFeatureLabel(feature: string): string {
  return FEATURE_LABELS[feature] ?? feature;
}
