import { mkdtempSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const buildDir = mkdtempSync(join(tmpdir(), "wardbrain-tests-"));
symlinkSync(join(process.cwd(), "node_modules"), join(buildDir, "node_modules"), "dir");

function run(command, args) {
  const result = spawnSync(command, args, {
    stdio: "inherit",
    cwd: process.cwd(),
    env: {
      ...process.env,
      NODE_ENV: process.env.NODE_ENV ?? "test",
      WARDBRAIN_TEST_MODE: "1",
      WARDBRAIN_TEST_DB_FALLBACK_LOG_PATH: join(buildDir, "db-feature-phrase-fallback.log"),
    },
  });

  if (result.status !== 0) {
    rmSync(buildDir, { recursive: true, force: true });
    process.exit(result.status ?? 1);
  }
}

run("node", ["scripts/check-admin-test-import-coverage.mjs"]);

run("./node_modules/.bin/tsc", [
  "--outDir",
  buildDir,
  "--module",
  "nodenext",
  "--moduleResolution",
  "nodenext",
  "--target",
  "es2022",
  "--skipLibCheck",
  "true",
  "--noEmit",
  "false",
  "app/api/analyze-case/route.ts",
  "lib/application/analyzeCase.ts",
  "lib/differentialEngine.ts",
  "lib/familyRanking.ts",
  "lib/conditionPromotionRegistry.ts",
  "lib/diagnosisAliases.ts",
  "lib/diagnosisScoring.ts",
  "lib/featureExtractor.ts",
  "lib/diagnosisBoosts.ts",
  "lib/diagnosisRules.ts",
  "lib/featureLabels.ts",
  "lib/normalizeInput.ts",
  "lib/nextStepsRules.ts",
  "lib/presentationFamilies.ts",
  "lib/redFlagRules.ts",
  "lib/wardbrainLookup.ts",
  "lib/guidelineRules.ts",
  "lib/types.ts",
  "lib/types/index.ts",
  "types/next-auth.d.ts",
  "lib/domain/conditionPromotionRegistry.ts",
  "lib/domain/diagnosisAliases.ts",
  "lib/domain/diagnosisBoosts.ts",
  "lib/domain/diagnosisDefinitionEvaluator.ts",
  "lib/domain/diagnosisSlug.ts",
  "lib/domain/diagnosisRules.ts",
  "lib/domain/diagnosisScoring.ts",
  "lib/domain/familyRanking.ts",
  "lib/domain/featureExtractor.ts",
  "lib/domain/featureLabels.ts",
  "lib/domain/featureSlug.ts",
  "lib/domain/guidelineRules.ts",
  "lib/domain/labs/deriveLabFeatures.ts",
  "lib/domain/labs/index.ts",
  "lib/domain/labs/interpretAbg.ts",
  "lib/domain/labs/interpretFbc.ts",
  "lib/domain/labs/interpretLfts.ts",
  "lib/domain/labs/interpretUes.ts",
  "lib/domain/labs/labDiagnosisModifiers.ts",
  "lib/domain/labs/labTypes.ts",
  "lib/domain/labs/labSafetyRules.ts",
  "lib/domain/labs/referenceRanges.ts",
  "lib/domain/nextStepsRules.ts",
  "lib/domain/normalizeInput.ts",
  "lib/domain/presentationBlocks/acuteAbdominalPain.ts",
  "lib/domain/presentationBlocks/headache.ts",
  "lib/domain/presentationBlocks/index.ts",
  "lib/domain/presentationFamilies.ts",
  "lib/domain/redFlagRules.ts",
  "lib/domain/wardbrainLookup.ts",
  "lib/guidelines/guidelineRegistry.ts",
  "lib/llm/blockFeatureSets.ts",
  "lib/llm/client.ts",
  "lib/llm/config.ts",
  "lib/llm/evaluation.ts",
  "lib/llm/extractFeatures.ts",
  "lib/llm/mergeFeatures.ts",
  "lib/llm/promptBuilders.ts",
  "lib/llm/schema.ts",
  "scripts/evaluate-cases.ts",
  "scripts/evaluate-lab-workflow.ts",
  "lib/testing/evaluateClinicalTestCase.ts",
  "types/wardbrain.ts",
  "content/wardbrain_core_pilot_app_ready.ts",
  "tests/domain.featureExtractor.test.mts",
  "tests/evaluateClinicalTestCase.test.mts",
  "tests/featureExtractionCases.ts",
  "tests/featureExtraction.test.mts",
  "tests/diagnosisAliases.test.mts",
  "tests/conditionPromotionRegistry.test.mts",
  "tests/acuteAbdominalPainDefinitions.test.mts",
  "tests/biochemicalRegressionCases.test.mts",
  "tests/breathlessnessV1.test.mts",
  "tests/bulkEvalCases.test.mts",
  "tests/chestPainV1.test.mts",
  "tests/confusionDeliriumV1.test.mts",
  "tests/diagnosisDefinitionEvaluator.test.mts",
  "tests/finalCalibration.test.mts",
  "tests/highPriorityCalibration.test.mts",
  "tests/hostileAcuteAbdominalCases.test.mts",
  "tests/guidelineRegistry.test.mts",
  "tests/headacheV1.test.mts",
  "tests/integration/analyzeCaseApi.test.mts",
  "tests/labDiagnosisModifiers.test.mts",
  "tests/labIntegration.test.mts",
  "tests/labWorkflowQa.test.mts",
  "tests/labs.test.mts",
  "tests/fixtures/messyPilotVignettes.ts",
  "tests/fixtures/headacheV1Cases.ts",
  "tests/fixtures/labWorkflowQaCases.ts",
  "tests/llmEvaluation.test.mts",
  "tests/llmExtractionScaffold.test.mts",
  "tests/messyPilotCases.test.mts",
  "tests/pilotHardeningV2.test.mts",
  "tests/targetedCalibration.test.mts",
  "tests/familyRanking.test.mts",
  "tests/nextSteps.test.mts",
  "tests/reasoningComparison.test.mts",
  "tests/wardbrainLookup.test.mts",
  "tests/trapCases.ts",
  "tests/trapCases.test.mts",
]);

run("node", [
  "--test",
  join(buildDir, "tests", "trapCases.test.mjs"),
  join(buildDir, "tests", "featureExtraction.test.mjs"),
  join(buildDir, "tests", "diagnosisAliases.test.mjs"),
  join(buildDir, "tests", "conditionPromotionRegistry.test.mjs"),
  join(buildDir, "tests", "acuteAbdominalPainDefinitions.test.mjs"),
  join(buildDir, "tests", "biochemicalRegressionCases.test.mjs"),
  join(buildDir, "tests", "breathlessnessV1.test.mjs"),
  join(buildDir, "tests", "bulkEvalCases.test.mjs"),
  join(buildDir, "tests", "chestPainV1.test.mjs"),
  join(buildDir, "tests", "confusionDeliriumV1.test.mjs"),
  join(buildDir, "tests", "diagnosisDefinitionEvaluator.test.mjs"),
  join(buildDir, "tests", "domain.featureExtractor.test.mjs"),
  join(buildDir, "tests", "evaluateClinicalTestCase.test.mjs"),
  join(buildDir, "tests", "finalCalibration.test.mjs"),
  join(buildDir, "tests", "highPriorityCalibration.test.mjs"),
  join(buildDir, "tests", "hostileAcuteAbdominalCases.test.mjs"),
  join(buildDir, "tests", "guidelineRegistry.test.mjs"),
  join(buildDir, "tests", "headacheV1.test.mjs"),
  join(buildDir, "tests", "integration", "analyzeCaseApi.test.mjs"),
  join(buildDir, "tests", "labDiagnosisModifiers.test.mjs"),
  join(buildDir, "tests", "labIntegration.test.mjs"),
  join(buildDir, "tests", "labWorkflowQa.test.mjs"),
  join(buildDir, "tests", "labs.test.mjs"),
  join(buildDir, "tests", "llmEvaluation.test.mjs"),
  join(buildDir, "tests", "llmExtractionScaffold.test.mjs"),
  join(buildDir, "tests", "messyPilotCases.test.mjs"),
  join(buildDir, "tests", "pilotHardeningV2.test.mjs"),
  join(buildDir, "tests", "targetedCalibration.test.mjs"),
  join(buildDir, "tests", "familyRanking.test.mjs"),
  join(buildDir, "tests", "nextSteps.test.mjs"),
  join(buildDir, "tests", "reasoningComparison.test.mjs"),
  join(buildDir, "tests", "wardbrainLookup.test.mjs"),
]);

rmSync(buildDir, { recursive: true, force: true });
